const GENERATED_TOOL_COVER_IDS = new Set([
  'ai-code-reviewer',
  'ai-excel-formula',
  'ai-image-generator',
  'ai-meeting-minutes',
  'ai-prompt-generator',
  'ai-regex',
  'ai-svg-generator',
  'ai-text-polisher',
  'ai-translator',
  'ai-video-script',
  'ai-weekly-report',
  'ai-xiaohongshu',
  'ai-youtube-generator',
  'archive-converter',
  'ascii-table',
  'barcode-generator',
  'base-converter',
  'base64',
  'color-converter',
  'color-palette',
  'color-picker',
  'competitor-tracker',
  'crypto-symmetric',
  'etsy-fee-calculator',
  'hash-generator',
  'hex-string-converter',
  'image-compressor',
  'image-converter',
  'image-cropper',
  'image-to-base64',
  'image-to-ico',
  'image-to-pdf',
  'json-to-ts',
  'json-formatter',
  'jwt-debugger',
  'keyword-analyzer',
  'listing-generator',
  'logo-generator',
  'market-insights',
  'password-generator',
  'pdf-merge',
  'pdf-split',
  'pdf-to-image',
  'ppi-calculator',
  'qr-generator',
  'qr-scanner',
  'regex-tester',
  'rmb-converter',
  'short-url',
  'stripe-fee-calculator',
  'svg-to-png',
  'symbol-library',
  'text-analyzer',
  'text-cleaner',
  'text-diff',
  'time-converter',
  'timestamp-converter',
  'unit-converter',
  'unicode-converter',
  'url-encoder',
  'uuid-generator',
  'xml-json',
]);

export function hasGeneratedToolCover(toolId: string) {
  return GENERATED_TOOL_COVER_IDS.has(toolId);
}

export function getToolCoverPath(toolId: string) {
  return `/images/tools/${toolId}.png?v=2`;
}
