import type { TechnicalOverview } from '../../../types/tool-overview';

type BilingualOverview = {
  zh: TechnicalOverview;
  en: TechnicalOverview;
};

export const NET_TOOL_OVERVIEWS: Record<string, BilingualOverview> = {
  'short-url': {
    zh: {
      summary:
        '短链接生成工具用于将较长的原始 URL 转换为紧凑、易分享、易展示和易复制的短链接地址，有效缩减字符数并提升链接在不同传播渠道中的可读性和美观度。适合社交媒体帖子（如微博 140 字限制、Twitter/X 推文中链接占比控制）、短信和即时通讯通知（如 SMS 计费按字符数收费场景、企业微信/飞书/钉钉群消息中嵌入追踪链接）、邮件营销活动（Newsletter / EDM 中避免过长 URL 被邮件客户端截断或触发垃圾过滤器）、二维码落地页（短链接生成的二维码图案更简洁、容错率更高、扫描识别速度更快）、线下印刷物料（名片、宣传单页、易拉宝、包装盒上的链接更短更友好）、客服回复模板和工单系统中的参考链接、App 内分享卡片中的跳转地址，以及包含多个 UTM 追踪参数的营销分析链接（来源、媒介、广告系列、关键词等参数组合常导致 URL 超过数百字符）。工具通过调用站点后端短链接口，向多个短链服务商同步请求生成短链接，并在页面中以卡片列表形式展示所有线路的结果，每条结果标注服务商来源，第一条优质结果自动标记为"推荐"，方便用户根据自身需求（如访问速度、域名权威性、国内/境外可访问性）选择最合适的短链接进行传播使用。',
      input:
        '一个以 http:// 或 https:// 开头的完整长链接地址。链接可以包含多级路径（如 /category/subcategory/product-detail）、多个查询参数（如 ?id=123&ref=homepage）、标准 UTM 追踪参数（utm_source、utm_medium、utm_campaign、utm_term、utm_content 等自定义参数组合）、页面锚点（如 #section-3），以及经过 encodeURIComponent 编码的特殊字符和中文路径（如 /搜索?q=关键词 → /%E6%90%9C%E7%B4%A2?q=%E5%85%B3%E9%94%AE%E8%AF%8D），工具会原样保留编码内容连同完整 URL 一并提交。输入框为空时点击生成按钮不会触发提交；当输入内容不以 http:// 或 https:// 开头时，页面会展示格式校验提示（如"请输入有效的 HTTP(S) 链接"），防止将普通文本、邮箱地址或非 URL 字符串误发送至短链接口导致无效请求。输入框内展示地球图标以引导用户输入 URL，placeholder 文本提供典型长链格式示例（如 https://example.com/very/long/path/with?params=123）。',
      output:
        '由后端短链服务查询多个服务商后返回的一组短链接结果，以卡片列表形式在右侧面板展示。每条卡片结果包含三项信息：服务商名称（以大写标签形式展示，如 TINYURL、S.ST、BIT.LY 等，帮助用户区分不同线路的来源）；短链接地址（以等宽字体显著展示，颜色可一键点击复制到系统剪贴板，复制成功后按钮图标切换为对勾并短暂显示"已复制"状态，2 秒后自动恢复为复制图标）；以及可选的备注说明（以灰色小字展示，如"国内访问较快"或"适合国际分享"，由后端接口附带提供，帮助用户做出选择）。第一条结果自动标记为绿色"推荐"标签，代表后端综合评估后的首选短链。生成失败时，页面会在输入区下方展示红色背景的错误提示卡片（包含后端返回的具体错误信息或"请稍后重试"的通用提示），同时清空已有短链列表，避免用户基于过期或错误的结果进行操作。',
      processing:
        '用户点击生成按钮后，页面首先执行前端基础校验：去除输入内容首尾空白字符（String.trim()），检查是否为空（空值直接返回不发起请求），校验是否以 http 协议头开头（非 HTTP(S) 输入立即设置错误状态并中止后续流程）。校验通过后，组件进入加载状态（按钮文字切换为加载中动画图标、禁用重复点击），清空上一轮的错误信息和短链结果列表，通过浏览器原生 fetch API 向 /api/shorten 端点发送 POST 请求，请求头 Content-Type 设为 application/json，请求体（body）通过 JSON.stringify 序列化包含原始 URL 的对象 { url: url.trim() }。后端接口收到请求后向多个短链服务商（如 TinyURL、s.st、Bitly 等第三方 API）并行发起短链创建请求，汇总各服务商的返回结果后统一响应。组件接收响应并通过 response.json() 解析 JSON 数据：若 data.success 为 true 且 data.links 为非空数组，则将 links 数组设置到 shortLinks 状态，触发 React 重新渲染以展示各条短链结果卡片（第一条自动标记推荐标签）；若 data.success 为 false 或 data.links 不存在，则提取 data.error 字段作为错误消息抛出。复制操作调用 navigator.clipboard.writeText(linkUrl) 将短链文本写入系统剪贴板，复制成功后将对应卡片的 copiedId 状态更新以触发图标切换和"已复制"文案展示，2 秒后通过 setTimeout 重置 copiedId 恢复初始状态。新标签页打开链接使用原生 <a> 标签的 target="_blank" 和 rel="noopener noreferrer" 属性以安全方式在新页签中打开短链，方便用户验证跳转目标是否正确。整个请求-响应-渲染流程均由页面状态管理驱动，实际短链创建的鉴权、频率限制、服务商调度和高可用策略由后端接口统一处理，前端仅负责交互展示层。',
      modes: ['HTTP(S) 协议校验', '多线路并行生成', '服务商标注区分', '推荐结果自动标记', '逐条一键复制（剪贴板 API + 状态反馈）', '新标签页安全打开验证', '加载态按钮禁用', '错误信息明确展示'],
      example: {
        title: '短链接生成输入到输出示例',
        input: 'https://example.com/products/spring-launch?utm_source=newsletter&utm_medium=email&utm_campaign=may_promo',
        output:
          '服务商 A (推荐): https://short.example/aB12cD\n服务商 B: https://s.example/9xYzW3\n\n选择任一短链接复制后用于社媒帖子、短信通知、邮件营销或二维码落地页。',
        inputLanguage: 'text',
        outputLanguage: 'text',
      },
    },
    en: {
      summary:
        'The Short URL tool converts lengthy original URLs into compact, easy-to-share, easy-to-display, and easy-to-copy short-link addresses, effectively reducing character count and improving link readability and aesthetics across distribution channels. Ideal for social media posts (e.g. Weibo\'s 140-character limit, controlling link ratio in Twitter/X posts), SMS and instant messaging notifications (e.g. SMS billing per character, embedding tracking links in WeCom/Feishu/DingTalk group messages), email marketing campaigns (Newsletter / EDM — avoiding overly long URLs being truncated by email clients or triggering spam filters), QR code landing pages (short links produce cleaner QR patterns with higher fault tolerance and faster scan recognition), printed marketing materials (business cards, flyers, roll-up banners, packaging — shorter, friendlier links), customer support reply templates and ticketing system reference links, in-app share card deeplink addresses, and marketing analytics URLs containing multiple UTM tracking parameters (combinations of source, medium, campaign, term, and content parameters often push URLs past several hundred characters). The tool calls the site backend shortening endpoint to simultaneously request short links from multiple providers, then displays all results in a card list with each result labeled by provider source. The top-quality result is automatically marked as "Recommended," allowing users to select the most suitable short link based on their specific needs — such as access speed, domain authority, or domestic/international reachability.',
      input:
        'A complete long URL starting with http:// or https://. The URL may include multi-level paths (e.g. /category/subcategory/product-detail), multiple query parameters (e.g. ?id=123&ref=homepage), standard UTM tracking parameters (custom combinations of utm_source, utm_medium, utm_campaign, utm_term, utm_content, etc.), page anchors (e.g. #section-3), and special characters or CJK paths that have been encodeURIComponent-encoded (e.g. /search?q=keyword → /%E6%90%9C%E7%B4%A2?q=%E5%85%B3%E9%94%AE%E8%AF%8D). The tool preserves the encoded content as-is and submits it together with the full URL. Empty input will not trigger submission when the Generate button is clicked. When the input does not start with http:// or https://, the page displays a format validation message (e.g. "Please enter a valid HTTP(S) link"), preventing plain text, email addresses, or non-URL strings from being mistakenly sent to the shortening endpoint and causing invalid requests. The input field displays a globe icon to guide users toward entering a URL, and the placeholder text provides a typical long-link format example (e.g. https://example.com/very/long/path/with?params=123).',
      output:
        'A set of short-link results returned by the backend after querying multiple providers, displayed as a card list in the right-hand panel. Each result card contains three pieces of information: the provider name (displayed as an uppercase label, e.g. TINYURL, S.ST, BIT.LY, helping users distinguish between different provider sources); the short link address (prominently displayed in monospace font, clickable to copy to the system clipboard with one click — upon successful copy, the button icon switches to a checkmark and briefly displays a "Copied" state, automatically reverting to the copy icon after 2 seconds); and an optional descriptive note (shown in smaller grey text, e.g. "Faster domestic access" or "Best for international sharing," provided by the backend to assist user choice). The first result is automatically marked with a green "Recommended" label, representing the backend\'s top pick after comprehensive evaluation. When generation fails, the page displays a red-background error card below the input area, showing either the specific error message returned by the backend or a generic "Please try again later" prompt, while simultaneously clearing the existing short-link list to prevent users from acting on stale or incorrect results.',
      processing:
        'When the user clicks the Generate button, the page first performs frontend basic validation: trims leading and trailing whitespace from the input (String.trim()), checks for emptiness (returns immediately without initiating a request on empty input), and verifies that the input starts with the http protocol prefix (non-HTTP(S) input immediately sets an error state and aborts the subsequent flow). After passing validation, the component enters a loading state (button text switches to a spinning loader icon, repeated clicks are disabled), clears any previous error messages and short-link result list, and sends a POST request to the /api/shorten endpoint via the browser\'s native fetch API with Content-Type set to application/json and the request body serialized via JSON.stringify as the object { url: url.trim() }. Upon receiving the request, the backend endpoint initiates parallel short-link creation requests to multiple providers (e.g. TinyURL, s.st, Bitly, and other third-party APIs), aggregates each provider\'s returned result, and sends back a unified response. The component receives the response and parses the JSON data via response.json(): if data.success is true and data.links is a non-empty array, the links array is set to the shortLinks state, triggering a React re-render to display each short-link result card (with the first card automatically receiving a recommended tag); if data.success is false or data.links is absent, the data.error field is extracted and thrown as an error message. The copy operation calls navigator.clipboard.writeText(linkUrl) to write the short-link text to the system clipboard. On successful copy, the copiedId state for that card is updated to trigger an icon switch and a "Copied" label, then reset after 2 seconds via setTimeout. Opening a link in a new tab uses a native <a> tag with target="_blank" and rel="noopener noreferrer" attributes to safely open the short link in a new tab, allowing users to verify that the redirect target is correct. The entire request-response-render pipeline is driven by page state management; actual short-link creation logic — including authentication, rate limiting, provider scheduling, and high-availability strategies — is handled uniformly by the backend endpoint, while the frontend is responsible solely for the interactive presentation layer.',
      modes: ['HTTP(S) protocol validation', 'Multi-provider parallel generation', 'Provider label distinction', 'Automatic recommended-result marking', 'Per-link one-click copy (Clipboard API + state feedback)', 'Safe new-tab open verification', 'Loading-state button disable', 'Explicit error display'],
      example: {
        title: 'Short URL generation input-to-output example',
        input: 'https://example.com/products/spring-launch?utm_source=newsletter&utm_medium=email&utm_campaign=may_promo',
        output:
          'Provider A (Recommended): https://short.example/aB12cD\nProvider B: https://s.example/9xYzW3\n\nCopy either short URL for social media posts, SMS notifications, email marketing, or QR code landing pages.',
        inputLanguage: 'text',
        outputLanguage: 'text',
      },
    },
  },
};
