import type { TechnicalOverview } from '../../../types/tool-overview';

type BilingualOverview = {
  zh: TechnicalOverview;
  en: TechnicalOverview;
};

export const AI_TOOL_OVERVIEWS: Record<string, BilingualOverview> = {
  'ai-youtube-generator': {
    zh: {
      summary:
        'YouTube 标题与简介生成器用于根据视频主题、目标观众、推荐语气和输出语言，通过 AI 模型生成可直接用于 YouTube 发布页面的标题、SEO 优化简介、视频标签和缩略图创意方案。适合内容创作者在选题确定后快速探索多种包装方向与标题变体（如教程类、评测类、Vlog 类不同的标题策略），频道运营人员为多个视频批量准备搜索引擎友好的描述文本和关键词标签，发布前团队统一标题风格和品牌话术，以及面向不同语言市场的本地化内容团队将视频包装适配为特定语种和平台语境。工具借助服务端流式传输（Server-Sent Events）逐步返回生成内容，页面会实时追加文本片段，避免在完整结果生成后才一次性渲染的长等待空白，用户在内容渐进出现的同时即可开始预览和评估方向是否合适。',
      input:
        '四个核心输入参数：视频主题或核心内容（必填）、目标观众描述、推荐语气和输出语言。主题可以是一句话的核心选题，也可以包含更丰富的上下文——如视频大纲结构、产品核心卖点、教程的步骤列表、目标关键词覆盖要求、活动推广背景或品牌合作信息。目标观众用于约束通用表达方式以贴近特定人群，例如"咖啡制作初学者""SaaS 创业者""在校大学生""数码产品爱好者"或"海外跨境电商买家"等，直接决定了标题的用词选择和说服方式。语气选项控制输出文案的情感色彩和沟通策略：教育型（Educational）输出更强调知识传递和分步讲解；吸引点击型（Click-worthy）输出加入数字、感叹、悬念等诱因元素；戏剧化（Dramatic）输出侧重故事感和情绪张力。输出语言支持中文、英文、日文、韩文等多种语言，方便面向不同 YouTube 市场的频道直接获取目标语种素材。',
      output:
        '结构化的 YouTube 发布素材包，AI 模型通常按约定格式输出四大板块：标题区域（[TITLE]）提供 3-5 个备选标题，覆盖不同吸引策略和关键词侧重；简介描述区域（[DESCRIPTION]）生成符合 YouTube SEO 最佳实践的描述文本，包含关键词、时间戳导航、相关链接占位和订阅引导语；标签区域（[TAGS]）按热度与相关性输出一系列逗号分隔的标签词，便于直接粘贴到 YouTube 标签栏；缩略图创意区域（[THUMBNAIL_IDEAS]）提供视觉方向建议，包括主要元素、配色倾向、文字叠加和表情引导。页面通过正则匹配 [TITLE]、[DESCRIPTION]、[TAGS]、[THUMBNAIL_IDEAS] 等标记自动拆分段落，并为每个段落生成独立的复制按钮，用户可以按需复制指定区域而不必全选后再二次删除。如果 AI 返回的内容不是标准分段格式，页面会以 Markdown 格式渲染全文结果，同样保留整体复制能力。异常情况下（如网络超时或服务端错误）会在输出面板展示明确错误提示并使输入表单保持可用以便修改后重试。',
      processing:
        '用户点击生成按钮后，页面首先收集四个输入参数（主题 topic、观众 audience、语气 tone、语言 targetLang 及当前界面 locale），将其组装为 JSON 载荷通过 fetch API 以 POST 方式发送至 /api/youtube-generator 端点，请求头 Content-Type 设为 application/json。服务端收到请求后向 AI 模型发起生成调用，并以 SSE（Server-Sent Events，text/event-stream）格式逐步向客户端推送数据。前端通过 ReadableStream 读取响应体：每个 SSE data 片段的原始字节被 TextDecoder 解码为字符串，经 JSON.parse 解析后提取其中的 content 字段（即模型实时生成的文本片段），通过 React 的 setState（函数式更新 prev => prev + chunk.content）逐个片段追加累积到结果状态中，浏览器同步将增量文本渲染到输出面板，实现流式打字效果。当 SSE 流结束时（done 事件或连接关闭），页面将完整结果文本传入分段解析函数：通过正则逐行扫描寻找 [TITLE]、[DESCRIPTION]、[TAGS]、[THUMBNAIL_IDEAS] 等标记，在每两个标记或标记与文本边界之间按索引范围切分出独立段落，生成段落类型数组供 UI 渲染分段卡片。复制操作调用 navigator.clipboard.writeText 将指定段落的完整文本写入系统剪贴板，按钮短暂显示"已复制"状态后通过 setTimeout 恢复。若 fetch 失败或 JSON 解析异常，页面在 catch 块中设置错误状态并停止加载指示器，用户可修改输入参数后重新点击生成。',
      modes: ['视频主题输入', '目标观众定向', '语气风格选择（教育/点击吸引力/戏剧化）', '多语言输出（中/英/日/韩等）', 'SSE 流式实时生成', '[TITLE]/[DESCRIPTION]/[TAGS]/[THUMBNAIL_IDEAS] 分段自动识别', '分段独立复制', 'Markdown 降级渲染'],
      example: {
        title: 'YouTube 素材生成输入到输出示例',
        input: '视频主题: 在家制作咖啡拉花 — 从零开始学打奶泡和基础图案\n目标观众: 咖啡制作初学者\n语气: 教育型\n输出语言: 中文',
        output:
          '[TITLE]\n1. 新手也能学会的咖啡拉花入门教程 | 从打奶泡到爱心图案\n2. 零基础咖啡拉花：30 分钟做出你的第一杯拿铁艺术\n\n[DESCRIPTION]\n本视频面向完全零基础的咖啡爱好者，从牛奶的选择与打发温度开始，逐步讲解奶泡质量控制、注入角度和基础拉花图案（爱心、树叶）的完整手法……\n\n[TAGS]\n咖啡拉花, 咖啡教程, 拿铁艺术, 新手咖啡, 意式咖啡, 奶泡技巧\n\n[THUMBNAIL_IDEAS]\n左侧：一杯完成拉花的拿铁特写（爱心图案清晰），右侧：文字"零基础学会拉花"，背景暖色调木纹桌面。',
        inputLanguage: 'text',
        outputLanguage: 'markdown',
      },
    },
    en: {
      summary:
        'The YouTube Title & Description Generator leverages AI to create publish-ready titles, SEO-optimized descriptions, tags, and thumbnail ideas from a video topic, target audience, tone, and output language. Ideal for content creators exploring multiple packaging angles and title variants after locking in a topic (e.g. tutorial-style, review-style, and vlog-style title strategies); channel operators batch-preparing search-friendly descriptions and keyword tags for multiple videos; teams standardizing title style and brand phrasing before publishing; and localization teams adapting video packaging for specific languages and platform contexts across different YouTube markets. The tool streams results back via Server-Sent Events so content appears progressively rather than after a long blank wait, allowing users to preview and evaluate creative direction while generation is still underway.',
      input:
        'Four core input parameters: video topic or core message (required), target audience description, recommended tone, and output language. The topic can be a one-line idea or a richer brief including video outline structure, key product selling points, tutorial step lists, target keyword coverage requirements, campaign background, or brand collaboration details. The target audience narrows wording to fit a specific group — such as "coffee beginners," "SaaS founders," "college students," "tech enthusiasts," or "cross-border e-commerce buyers" — directly influencing title word choice and persuasion approach. The tone option controls the emotional character of the output: Educational emphasizes knowledge transfer and step-by-step explanation; Click-worthy incorporates numbers, exclamations, and curiosity gaps; Dramatic leans into storytelling and emotional tension. Output language supports Chinese, English, Japanese, Korean, and other languages, enabling channels targeting different YouTube markets to obtain native-language assets directly.',
      output:
        'A structured YouTube publishing asset package. The AI model typically outputs four blocks by convention: the Title area ([TITLE]) provides 3-5 title candidates covering different hook strategies and keyword focuses; the Description area ([DESCRIPTION]) generates YouTube SEO best-practice description text with keywords, timestamp navigation placeholders, related link slots, and subscribe CTAs; the Tags area ([TAGS]) outputs a comma-separated list of tags sorted by relevance and popularity, ready to paste into the YouTube tags field; the Thumbnail Ideas area ([THUMBNAIL_IDEAS]) supplies visual direction suggestions including main elements, color preferences, text overlay ideas, and facial expression cues. The page automatically detects [TITLE], [DESCRIPTION], [TAGS], and [THUMBNAIL_IDEAS] markers via regex, splitting the output into sections with independent copy buttons for each — users can copy only the section they need without selecting, copying all, and then deleting unwanted parts. If the AI response is not in the expected section format, the full result is rendered as Markdown while still supporting full-text copy. On errors (e.g. network timeout or server failure), the output panel shows a clear error message and keeps the input form available for adjustment and retry.',
      processing:
        'When the user clicks Generate, the page first collects the four input parameters (topic, audience, tone, targetLang, and the current UI locale), assembles them into a JSON payload, and sends a POST request to the /api/youtube-generator endpoint via fetch with Content-Type set to application/json. The server initiates an AI model generation call and progressively pushes data to the client in SSE (Server-Sent Events, text/event-stream) format. The frontend reads the response body via ReadableStream: each raw SSE data chunk byte sequence is decoded to a string via TextDecoder, parsed via JSON.parse to extract the content field (the model\'s real-time generated text fragment), and accumulated into the result state via React\'s setState (functional updater prev => prev + chunk.content). The browser synchronously renders the incremental text into the output panel, achieving a streaming typewriter effect. When the SSE stream ends (done event or connection close), the page passes the complete result text to a section-parsing function: it scans line by line with regex for [TITLE], [DESCRIPTION], [TAGS], [THUMBNAIL_IDEAS] markers, splits the text into independent sections at each boundary between two markers or a marker and text boundary by index range, and generates a section-type array for the UI to render as section cards. Copy operations call navigator.clipboard.writeText to write the specified section\'s full text to the system clipboard, and the button briefly shows a "Copied" state before resetting via setTimeout. If fetch fails or JSON parsing throws, the page sets an error state in the catch block and stops the loading indicator, allowing the user to adjust input and retry.',
      modes: ['Video topic input', 'Target audience targeting', 'Tone selection (Educational / Click-worthy / Dramatic)', 'Multilingual output (EN/ZH/JA/KO etc.)', 'SSE real-time streaming generation', 'Auto section detection: [TITLE]/[DESCRIPTION]/[TAGS]/[THUMBNAIL_IDEAS]', 'Per-section independent copy', 'Markdown fallback rendering'],
      example: {
        title: 'YouTube asset generation input-to-output example',
        input: 'Topic: Making latte art at home — from milk frothing to basic patterns\nAudience: Complete coffee beginners\nTone: Educational\nLanguage: English',
        output:
          '[TITLE]\n1. Beginner Latte Art Tutorial: From Milk Frothing to Heart Pattern\n2. Zero to Latte Art in 30 Minutes — Your First Pour\n\n[DESCRIPTION]\nIn this video, designed for absolute beginners, we cover everything from milk selection and steaming temperature to foam quality control, pouring angle, and basic latte art patterns (heart, rosetta)…\n\n[TAGS]\nlatte art, coffee tutorial, beginner coffee, espresso, milk frothing, home barista\n\n[THUMBNAIL IDEAS]\nLeft: Close-up of a finished latte with clear heart pattern. Right: Overlay text "Latte Art from Zero." Background: warm-toned wooden tabletop.',
        inputLanguage: 'text',
        outputLanguage: 'markdown',
      },
    },
  },

  'ai-prompt-generator': {
    zh: {
      summary:
        'AI 绘画提示词生成器用于将简短的中文或英文画面创意扩展为结构完整、语义丰富的高质量英文提示词，专为 Midjourney、Stable Diffusion、DALL·E、NovelAI 等主流图像生成模型的提示词格式优化。适合视觉设计师在草图阶段快速生成不同风格方向的提示词以探索视觉可能性（如同一主题在摄影写实、动漫手绘、赛博朋克、3D 渲染、油画质感、Logo 矢量、水彩淡彩和素描线稿等风格下的差异化呈现），新媒体运营人员为公众号封面、小红书配图、短视频封面和营销海报批量产出 AI 绘图提示词，产品设计团队为概念验证、用户访谈材料或 Demo 界面快速生成概念图提示，内容创作者为专栏封面、视频缩略图或品牌素材准备多套视觉方案，以及需要将纯中文创意转换为英文模型更易理解的标准提示词的创作者。工具通过流式接口返回多套方案，每套方案包含英文主提示词和中英文辅助解释，支持逐方案独立复制。',
      input:
        '两个核心参数：创意主题或画面描述（必填）和目标艺术风格（从预设风格列表中选择）。主题可以是简单对象，例如"一只戴着墨镜喝咖啡的猫"，也可以包含丰富的视觉上下文——场景环境（如巴黎露天咖啡馆、赛博朋克雨夜街道）、镜头角度与焦距（如 50mm 镜头特写、鸟瞰广角）、材质与表面属性（如磨砂金属、透明玻璃、丝绒面料）、光线与色调方向（如金色逆光、冷蓝霓虹、清晨柔光）、构图参考（如三分法构图、居中对称、引导线）、颜色约束（如 Monochromatic Blue、Pastel Palette）、情绪基调（如宁静孤独、未来科技感）和应用用途（如 App 启动页、Banner 配图、社交媒体帖子）。风格选项目前已涵盖 Photorealistic（摄影写实）、Anime（动漫手绘）、Cyberpunk（赛博朋克）、3D Render（3D 渲染）、Oil Painting（油画）、Minimalist Logo（极简 Logo）、Watercolor（水彩）和 Pencil Sketch（素描）八种主流风格，选择后 AI 会在提示词中注入该风格的典型参数词（如"Unreal Engine 5 render, octane render, volumetric lighting"对应 3D 渲染风格）。',
      output:
        '一组以分隔线和序号分段的绘画提示词方案（通常为 2-3 套），每套包含：方案标题（如"Prompt 1"）、英文主提示词（由多个逗号分隔的英文视觉关键词短语组成，按主体 → 场景 → 风格 → 镜头 → 光线 → 参数 → 分辨率的结构排列，可直接粘贴至 Midjourney / Stable Diffusion 等工具的提示词输入框）、以及中英文解释或补充说明（解释本方案的视觉策略、适合的参数搭配、可选的 negative prompt 建议、以及如果需要修改可以从哪些方向调整）。页面按连续等号分隔符（====）拆分多套方案，再通过 Markdown 标题和正文规则解析出提示词正文与说明段落。每套方案渲染为独立卡片并配有专属复制按钮，点击后仅复制该方案的英文主提示词部分，适合逐方案测试。返回内容异常时展示错误提示，空状态保留输入区域供用户随时修改参数重新尝试。',
      processing:
        '用户点击生成后，页面将输入的主题文本（topic）、选择的风格标识（style，如 "photorealistic""cyberpunk" 等）、当前界面语言（locale）和输出目标语言组合为 JSON 载荷，通过 fetch 以 POST 方式发送至 /api/ai-prompt-generator 端点。服务端将主题和风格信息拼接入 AI 模型 prompt 模板——模板以英文向模型下达指令："You are a professional prompt engineer. Based on the following topic and style, generate 2-3 complete image prompts optimized for Midjourney/Stable Diffusion..."，模型按 SSE 流式返回生成结果。前端通过 ReadableStream 读取事件流：每个 SSE 片段由 TextDecoder 解码为字符串，JSON.parse 提取 content 字段后，通过 React 状态累加函数 prev + chunk.content 实时追加到输出区域。流式传输结束后，页面进入渲染解析阶段：使用连续等号（====）作为多方案分隔符，将完整文本拆分为独立的方案数组；再对每个方案块应用 Markdown 解析（react-markdown + remark-gfm），识别其中的标题（方案名）、代码块或粗体提示词正文、普通段落文本（解释说明）。每个方案块各自分配一个复制按钮，点击时通过 navigator.clipboard.writeText 仅复制该方案的英文提示词正文（过滤掉解释说明），复刻成功后按钮状态切换为"已复制"并 2 秒后恢复。若 fetch 请求失败或服务端返回异常，页面在 catch 块中设置错误提示状态，允许用户回过头调整主题描述或切换风格后重试。',
      modes: ['主题创意输入（支持详细上下文）', '8 种艺术风格预设（摄影/动漫/赛博/3D/油画/Logo/水彩/素描）', '多方案并行生成（2-3 套）', '英文主提示词输出', '中文说明辅助（解释视觉策略和参数建议）', 'SSE 流式实时生成', '每套方案独立复制', 'Markdown 结构化渲染'],
      example: {
        title: 'AI 绘画提示词生成输入到输出示例',
        input: '主题: 一只穿着风衣的猫站在赛博朋克雨夜街头，霓虹灯倒影在地面水洼中，电影感灯光\n风格: 赛博朋克',
        output:
          'Prompt 1\nA noir-style anthropomorphic cat in a trench coat standing on a rainy cyberpunk street at night, neon signs reflecting in puddles, cinematic volumetric fog, wet asphalt, blue and magenta rim lighting, shallow depth of field, shot on 35mm anamorphic lens, hyper-detailed fur texture, Blade Runner aesthetic --ar 16:9 --v 6\n\n说明: 这套提示词以《银翼杀手》视觉风格为参考，强调雨夜氛围、霓虹色调和电影级虚化。适合 Midjourney v6 使用，可添加 --no text, watermark 排除多余元素。',
        inputLanguage: 'text',
        outputLanguage: 'text',
      },
    },
    en: {
      summary:
        'The AI Prompt Generator expands short visual ideas — in Chinese or English — into rich, structured, high-quality English prompts optimized for the prompt formats of mainstream image generation models including Midjourney, Stable Diffusion, DALL·E, and NovelAI. Ideal for visual designers quickly exploring prompts across different stylistic directions during the sketching phase (e.g. the same subject rendered in photorealistic, anime, cyberpunk, 3D render, oil painting, logo vector, watercolor, and pencil sketch styles); social media operators batch-producing AI art prompts for WeChat covers, Xiaohongshu illustrations, short-video thumbnails, and marketing posters; product design teams rapidly generating concept-image prompts for proof-of-concept validation, user interview materials, or demo interfaces; content creators preparing multiple visual options for column covers, video thumbnails, or brand assets; and creators who need to translate purely Chinese-language ideas into standardized English prompts that image models understand better. The tool returns multiple prompt options via streaming, each with an English main prompt and bilingual explanatory notes, with per-option independent copy.',
      input:
        'Two core parameters: the creative topic or image description (required) and a target art style (selected from a preset style list). The topic can be a simple object — e.g. "a cat wearing sunglasses drinking coffee" — or a richly detailed visual brief including: scene and environment (e.g. Parisian sidewalk café, cyberpunk rainy night street); camera angle and focal length (e.g. 50mm close-up, bird\'s-eye wide-angle); material and surface properties (e.g. frosted metal, transparent glass, velvet fabric); lighting and color direction (e.g. golden backlight, cool blue neon, soft morning glow); composition reference (e.g. rule of thirds, centered symmetry, leading lines); color constraints (e.g. Monochromatic Blue, Pastel Palette); emotional tone (e.g. serene solitude, futuristic tech); and intended usage (e.g. App splash screen, Banner illustration, social media post). The style selector currently covers eight mainstream styles — Photorealistic, Anime, Cyberpunk, 3D Render, Oil Painting, Minimalist Logo, Watercolor, and Pencil Sketch. When selected, the AI injects typical parameter keywords for that style into the prompt (e.g. "Unreal Engine 5 render, octane render, volumetric lighting" for 3D Render style).',
      output:
        'A set of prompt options (typically 2-3 options) separated by dividers and numbered, each containing: an option title (e.g. "Prompt 1"); the English main prompt (a sequence of comma-separated English visual keyword phrases arranged in the order: Subject → Scene → Style → Camera → Lighting → Parameters → Resolution, ready to paste directly into the prompt input of Midjourney, Stable Diffusion, etc.); and bilingual explanatory notes (explaining the visual strategy behind that option, suitable parameter combinations, optional negative prompt suggestions, and directions for further tuning). The page splits multiple options by repeated equals signs (====), then parses each block via Markdown heading and body rules to separate the prompt text from the explanation. Each option is rendered as an independent card with a dedicated copy button that copies only the English main prompt for that option — ideal for testing options one at a time. On error, a clear message is shown, and the input area remains available for the user to adjust and retry.',
      processing:
        'When the user clicks Generate, the page assembles the input topic text, the selected style identifier (e.g. "photorealistic", "cyberpunk"), the current UI locale, and the target output language into a JSON payload, sending it via fetch POST to the /api/ai-prompt-generator endpoint. The server splices the topic and style into an AI model prompt template — the template instructs the model in English: "You are a professional prompt engineer. Based on the following topic and style, generate 2-3 complete image prompts optimized for Midjourney/Stable Diffusion..." — and the model streams the result back via SSE. The frontend reads the event stream via ReadableStream: each SSE chunk is decoded by TextDecoder, the content field is extracted via JSON.parse, and the text is progressively accumulated into the output area via React setState (prev + chunk.content). After streaming completes, the page enters the render-parsing phase: repeated equals signs (====) are used as multi-option delimiters to split the full text into an array of independent options; then each option block is parsed via react-markdown with remark-gfm to identify headings (option name), code blocks or bold prompt body text, and plain paragraphs (explanatory notes). Each option block is assigned a copy button that calls navigator.clipboard.writeText to copy only that option\'s English prompt body (filtering out the explanation). On success, the button briefly shows "Copied" and resets after 2 seconds via setTimeout. If fetch fails or the server returns an error, the page sets an error state in the catch block, allowing the user to go back and adjust the topic description or switch styles before retrying.',
      modes: ['Creative topic input (supports detailed context)', '8 art style presets (Photorealistic / Anime / Cyberpunk / 3D / Oil Painting / Logo / Watercolor / Sketch)', 'Multi-option parallel generation (2-3 options)', 'English main prompt output', 'Chinese explanatory notes (visual strategy + parameter tips)', 'SSE real-time streaming generation', 'Per-option independent copy', 'Markdown structured rendering'],
      example: {
        title: 'AI prompt generation input-to-output example',
        input: 'Topic: A cat in a trench coat standing on a rainy cyberpunk street at night, neon signs reflecting in puddles, cinematic lighting\nStyle: Cyberpunk',
        output:
          'Prompt 1\nA noir-style anthropomorphic cat in a trench coat standing on a rainy cyberpunk street at night, neon signs reflecting in puddles, cinematic volumetric fog, wet asphalt, blue and magenta rim lighting, shallow depth of field, shot on 35mm anamorphic lens, hyper-detailed fur texture, Blade Runner aesthetic --ar 16:9 --v 6\n\nNote: This prompt references Blade Runner visuals, emphasizing rainy-night mood, neon tones, and cinematic bokeh. Works well with Midjourney v6. Add --no text, watermark to exclude unwanted elements.',
        inputLanguage: 'text',
        outputLanguage: 'text',
      },
    },
  },

  'ai-weekly-report': {
    zh: {
      summary:
        'AI 周报生成器用于将零散、口语化甚至不完整的工作记录整理为结构清晰、语气专业一致、可直接提交或经微调后使用的 Markdown 格式周报。适合需要定期向上级、团队或客户汇报进展的个人贡献者（开发工程师、产品经理、设计师、运营专员等），负责汇总团队多成员工作并合并为统一周报的项目经理或技术负责人，进行项目 Sprint 回顾和迭代复盘总结的敏捷团队，需要向导师或学校提交实习周报的实习生，以及希望将日常随手记录的任务碎片格式化为正式文档以便归档和绩效回顾的职场人士。工具支持四种输出语气——Professional（专业正式，适合向上汇报和对外交付）、Concise（简明扼要，适合快节奏团队和快速同步）、Detailed（详尽具体，包含背景、过程、成果和数据的完整叙事）和 Action-Oriented（结果导向，以成果和下一步行动为重心）——用户根据汇报对象和场景选择最合适的风格，AI 自动适配语言组织方式。',
      input:
        '三个核心文本输入字段和语气选择：本周完成事项（必填）——可输入任务列表、需求编号或用户故事 ID（如"STORY-1234 登录模块重构"）、项目里程碑节点（如"完成 V2.1 前端发布"）、口语化的随手记录（如"修了那个用户反馈的闪退 bug，跟后端对了下支付回调的格式"）；下周计划事项（选填，但推荐填写以获得更完整的周报结构）——用于生成规划段落，可列出待启动的需求、预期产出、关键里程碑和协作依赖；问题与风险（选填）——用于记录当前阻塞项、技术债、延期风险、外部依赖等待状态和需要协调的资源缺口；以及语气选项（Professional / Concise / Detailed / Action-Oriented），从预设值中选择一个以控制 AI 生成文本的措辞风格、段落密度和信息组织方式。输入不做本地持久化，切换页面或刷新后数据不保留，如需长期存档请将生成结果复制到文档工具中。',
      output:
        '一份结构化的 Markdown 格式周报，通常包含以下板块（AI 根据输入内容的有无自动决定是否生成对应板块）：本周工作完成情况——以分类或项目维度组织的已完成事项列表，每项包含简要描述和完成状态标记；关键成果与亮点——以量化和定性方式总结本周最有价值的工作产出或其业务影响；下周工作计划——按优先级排序的待推进事项，包含预计产出和依赖说明；风险与问题——当前遇到的阻塞、对项目进度的潜在影响和已采取或需要采取的应对措施；需要支持与协助——明确向谁、在哪方面需要协同或资源支持。输出以 react-markdown + remark-gfm 渲染为格式化的标题、列表、引用和代码块，阅读体验接近 Confluence / Notion 等文档工具的最终效果，支持一键复制全文 Markdown 源码或富文本内容直接粘贴到企业微信、飞书文档、邮件正文或项目管理平台的备注栏中。生成失败时在输出面板展示具体错误信息并保留输入表单状态以便用户调整后重新生成。',
      processing:
        '用户点击生成后，页面将四个核心参数——完成事项文本（done）、下周计划文本（todo）、问题风险文本（problems）和语气选项（tone，如 "professional""concise""detailed""action-oriented"）——连同当前界面语言 locale 一并组装为 JSON 载荷，通过 fetch API 以 POST 方式发送至 /api/ai-weekly-report 端点。服务端验证参数完整性后构建 AI 模型 system prompt："You are a professional weekly report writer. Based on the user\'s completed work, next-week plan, and identified risks, generate a structured weekly report in Markdown format with the specified tone..."，之后将用户的三段文本和语气参数注入 user prompt，模型按 SSE 流式返回生成的周报内容。前端通过 ReadableStream 并发逐块接收数据：每个 SSE 事件块以 TextDecoder 解码为纯文本，JSON.parse 提取 content 字段作为本次增量文本，通过 React 的 setState 函数式更新 prev + chunk.content 将新文本追加到结果字符串末尾，对应输出面板随之实时扩展。流式传输完成后，react-markdown（配合 remark-gfm 支持表格、任务列表等 GitHub Flavored Markdown 扩展语法）对完整 Markdown 文本进行渲染，生成带层级样式的可视化文档。复制功能通过 navigator.clipboard.writeText 复制完整 Markdown 原文，复制成功后按钮文字切换为"已复制"并在 2 秒后恢复。错误处理在 fetch catch 块中统一捕获：网络异常或服务端返回的非 success 响应均设置 error 状态字符串，输出区显示红色背景错误卡片，用户可调整输入文本后重新提交。',
      modes: ['本周完成事项（支持任务列表 / 项目编号 / 口语记录）', '下周计划事项', '问题风险与阻塞标记', '四种语气选择（专业 / 简明 / 详尽 / 结果导向）', 'Markdown 结构化输出（标题/列表/表格 GFM）', 'SSE 流式实时生成', '全文一键复制', '空字段智能跳过对应板块'],
      example: {
        title: 'AI 周报生成输入到输出示例',
        input: '本周完成: 1. 修复登录模块 session 过期后白屏问题；2. 完成用户中心接口文档 v2.0；3. 协助测试团队完成支付模块回归测试\n下周计划: 1. 接入微信支付 V3 回调接口；2. 重构订单列表查询性能（目标 < 200ms）\n问题风险: 第三方物流接口偶尔超时，已与对方技术对接排查中\n语气: 专业正式',
        output:
          '## 本周工作完成\n\n### 问题修复\n- 修复登录模块 session 过期后白屏问题，已上线生产环境。\n\n### 文档与协作\n- 完成用户中心接口文档 v2.0，已通过前后端联合评审。\n- 协助测试团队完成支付模块回归测试，覆盖 43 条用例。\n\n## 关键成果\n- 登录白屏问题修复后用户投诉量下降约 60%。\n\n## 下周计划\n- 接入微信支付 V3 回调接口，预计周三完成联调。\n- 重构订单列表查询，目标将响应时间优化至 200ms 以内。\n\n## 风险与问题\n- 第三方物流接口偶发超时，正在与对方技术团队联合排查。\n\n## 需要的支持\n- 暂无额外协调需求。',
        inputLanguage: 'text',
        outputLanguage: 'markdown',
      },
    },
    en: {
      summary:
        'The AI Weekly Report Generator transforms scattered, conversational, and sometimes incomplete work notes into a well-structured, professionally toned Markdown weekly report ready to submit or use with minor edits. Suitable for individual contributors (developers, product managers, designers, operations specialists) who need to report progress to managers, teams, or clients on a regular cadence; project managers and tech leads who aggregate multi-member work into a unified team report; agile teams conducting Sprint reviews and iteration retrospectives; interns submitting weekly internship reports to mentors or schools; and professionals who want to format daily jotted task fragments into formal documents for archival and performance review. The tool supports four output tones — Professional (formal and polished, suitable for upward reporting and external delivery), Concise (brief and to the point, for fast-paced teams and rapid sync), Detailed (comprehensive narrative including background, process, results, and data), and Action-Oriented (focused on outcomes and next steps) — allowing users to select the most appropriate style based on the report audience and context, with the AI auto-adapting language and organization accordingly.',
      input:
        'Three core text input fields and a tone selector: Completed Work This Week (required) — accepts task lists, issue IDs or user story IDs (e.g. "STORY-1234 Login module refactor"), project milestones (e.g. "Completed V2.1 frontend release"), or conversational rough notes (e.g. "Fixed that crash bug users reported, synced with backend on payment callback format"); Next Week Plan (optional but recommended for a more complete report structure) — used to generate the planning section, can list upcoming requirements, expected deliverables, key milestones, and collaboration dependencies; Problems & Risks (optional) — for recording current blockers, technical debt, delay risks, external dependency wait states, and resource gaps requiring coordination; and the Tone option (Professional / Concise / Detailed / Action-Oriented) selected from a preset list to control the AI-generated wording style, paragraph density, and information organization. Input is not persisted locally — data is lost on page navigation or refresh; for long-term archiving, copy the generated result into a document tool.',
      output:
        'A structured Markdown weekly report typically containing the following sections (the AI automatically decides whether to generate each section based on whether corresponding input is provided): Completed Work — a list of completed items organized by category or project dimension, each with a brief description and completion status; Key Results & Highlights — a quantitative and qualitative summary of this week\'s most valuable work output or business impact; Next Week Plan — priority-ordered upcoming tasks with expected deliverables and dependency notes; Risks & Issues — current blockers, potential impact on project timeline, and measures already taken or needed; Support Needed — clear identification of who, in what area, needs to collaborate or provide resources. Output is rendered via react-markdown + remark-gfm into formatted headings, lists, blockquotes, and code blocks with a reading experience close to the final rendered result in document tools like Confluence or Notion. A one-click full-text copy button provides the raw Markdown or rich-text content for pasting directly into WeCom, Feishu Docs, email body, or project management platform comment fields. On generation failure, the output panel displays the specific error message and preserves the input form state so the user can adjust and regenerate.',
      processing:
        'When the user clicks Generate, the page collects the four core parameters — completed work text (done), next-week plan text (todo), problems/risks text (problems), and tone option (tone, e.g. "professional", "concise", "detailed", "action-oriented") — together with the current UI locale, assembles them into a JSON payload, and sends it via fetch POST to the /api/ai-weekly-report endpoint. After validating parameter completeness, the server constructs an AI model system prompt: "You are a professional weekly report writer. Based on the user\'s completed work, next-week plan, and identified risks, generate a structured weekly report in Markdown format with the specified tone..." The user\'s three text blocks and tone parameter are then injected into the user prompt, and the model streams the generated report content back via SSE. The frontend receives data in parallel chunks via ReadableStream: each SSE event chunk is decoded to plain text by TextDecoder, the content field is extracted via JSON.parse as the incremental text for this segment, and React\'s setState functional updater (prev + chunk.content) appends new text to the end of the result string, with the output panel expanding in real time. After streaming completes, react-markdown (with remark-gfm supporting GitHub Flavored Markdown extensions such as tables and task lists) renders the full Markdown text into a visually styled hierarchical document. The copy function uses navigator.clipboard.writeText to copy the full Markdown source; on success the button text briefly switches to "Copied" and resets after 2 seconds. Error handling is unified in the fetch catch block: network exceptions or non-success server responses both set an error state string, and the output area displays a red-background error card while preserving the input for retry.',
      modes: ['Completed work (supports task lists / issue IDs / rough notes)', 'Next-week planning', 'Risks & blockers tracking', 'Four tone options (Professional / Concise / Detailed / Action-Oriented)', 'Markdown structured output (headings / lists / tables GFM)', 'SSE real-time streaming generation', 'Full-text one-click copy', 'Auto-skip sections for empty input fields'],
      example: {
        title: 'AI weekly report generation input-to-output example',
        input: 'Done: 1. Fixed login session-expiry white-screen issue; 2. Completed User Center API docs v2.0; 3. Assisted QA team with payment module regression testing\nNext: 1. Integrate WeChat Pay V3 callback; 2. Optimize order list query performance (target < 200ms)\nRisks: Third-party logistics API intermittent timeout, joint investigation underway with their tech team\nTone: Professional',
        output:
          '## Completed This Week\n\n### Bug Fixes\n- Fixed the login session-expiry white-screen issue; deployed to production.\n\n### Documentation & Collaboration\n- Completed User Center API documentation v2.0, approved in joint frontend/backend review.\n- Assisted QA team in completing payment module regression testing covering 43 test cases.\n\n## Key Results\n- User complaints dropped approximately 60% after the login white-screen fix.\n\n## Next Week Plan\n- Integrate WeChat Pay V3 callback API; target completion and joint debugging by Wednesday.\n- Refactor order list query to meet sub-200ms response-time target.\n\n## Risks & Issues\n- Third-party logistics API experiences intermittent timeouts; joint investigation ongoing with their engineering team.\n\n## Support Needed\n- No additional coordination needs at this time.',
        inputLanguage: 'text',
        outputLanguage: 'markdown',
      },
    },
  },

  'ai-video-script': {
    zh: {
      summary:
        'AI 视频脚本生成器用于将视频主题或核心创意扩展为分镜头完整、节奏张弛有度、可直接交付给拍摄和剪辑团队使用的结构化视频脚本。覆盖短视频（60 秒以内、适合抖音/TikTok/YouTube Shorts/Instagram Reels 的快节奏内容）和中长视频（3-10 分钟、适合 Bilibili/YouTube/视频号等平台的深度内容）两种时长规格，适配抖音、TikTok、YouTube Shorts、Instagram Reels、Bilibili、小红书视频和 YouTube 长视频七大目标平台。适合自媒体创作者在选题后快速拿到可执行的拍摄蓝图，品牌营销团队为产品发布、活动宣传或品牌故事制定口播 / 剧情脚本，知识科普作者将专业内容转化为通俗易懂的叙事结构，Vlog 创作者规划日常记录的节奏和情绪起伏，运营团队为信息流广告或营销投放批量生产脚本模板，以及企业内训团队为培训视频撰写分镜与讲解词。用户选择时长、平台和语气后，AI 自动生成包含开场钩子、分镜段落、画面建议、旁白 / 口播文案、字幕提示、转场节奏和结尾行动号召的完整脚本草稿。',
      input:
        '四个核心参数：视频主题或核心信息（必填）、预计时长（60s 以内 / 3-5 分钟 / 5-10 分钟）、目标平台（抖音 / TikTok / YouTube Shorts / Instagram Reels / Bilibili / 小红书 / YouTube）和脚本语气（教育型 / 娱乐型 / 故事叙述型 / 产品推销型 / 励志型）。主题输入框支持多行文本，可包含目标观众画像、产品核心卖点或功能介绍、故事冲突或情节线索、知识点大纲、转化目标（如引导点击链接、关注、评论互动、购买转化）和品牌调性约束（如"保持幽默风趣""突出科技专业感""温暖治愈系"）。时长选择直接影响脚本的信息密度和节奏起伏——60 秒以内短视频强调 3 秒黄金开场、密集信息点和强结尾钩子；3-5 分钟中视频为每 30-60 秒一个节奏点、中间可设小高潮；5-10 分钟长视频有更充分的时间铺垫、展开和收束。平台选择影响开场策略和口播方式——抖音/TikTok 强调前 3 秒抓人、Bilibili 可适当铺垫、YouTube 长视频可更从容地引导订阅。',
      output:
        '一份 Markdown 格式的视频拍摄脚本，通常按以下结构组织（AI 根据时长和平台自动调整板块密度和数量）：开场钩子——前 3-5 秒的注意力抓取设计（一个反常识问题、数据冲击、视觉冲突或利益承诺），附建议的画面和字幕配合；分镜段落——按时间线分段的拍摄单元，每段包含：镜号、时长、画面描述（构图、运镜、色彩、关键视觉元素）、旁白 / 口播文案、字幕关键提示词、音效 / 背景音乐建��和转场方式；节奏标注——在关键转折点标注节奏变化（加快、放缓、静默、冲击）以引导剪辑师后期处理；结尾行动号召——引导观众点赞、关注、评论、转发或点击链接的结束语。输出以 react-markdown + remark-gfm 渲染，阅读体验清晰分层，支持一键复制完整脚本全文，便于直接分享到飞书文档、Notion 等协作平台供拍摄和剪辑团队参照执行。生成失败时输出面板展示具体错误信息，输入参数保留不动方便修改后重试。',
      processing:
        '用户点击生成后，页面将四个输入参数——视频主题文本（topic）、时长选项（duration，如 "short""medium""long"）、平台标识（platform，如 "tiktok""youtube""bilibili" 等）、语气选项（tone）——连同当前界面语言 locale 组装为 JSON 载荷，通过 fetch API 以 POST 方式发送至 /api/ai-video-script 端点，Content-Type 设为 application/json。服务端接收到参数后构建 AI 模型 system prompt：根据所选时长约束脚本的总分镜数和每镜大约长度，根据平台调整开场策略和口播风格，根据语气控制整体语言色彩。模型按 SSE 流式逐步返回脚本内容，前端通过 ReadableStream 并发读取每个 SSE 事件：TextDecoder 将字节流解码为字符串，JSON.parse 提取 content 字段作为增量文本，通过 React 状态函数 prev + chunk.content 实时追加到累积结果中。流式传输完成后 react-markdown（配合 remark-gfm 插件支持 GitHub Flavored Markdown 的表格、任务列表等扩展）对完整 Markdown 文本进行渲染，生成带层级标题、列表和代码块的格式化文档。全文复制按钮通过 navigator.clipboard.writeText 将完整 Markdown 源码写入剪贴板，按钮反馈"已复制"后通过 setTimeout 在 2 秒后恢复默认文本。请求失败或服务端错误在 fetch catch 块中统一处理：error 状态设置为后端返回的错误消息或通用提示"生成失败，请稍后重试"，输出区域渲染红色背景错误卡片。',
      modes: ['视频主题多行输入（含受众/卖点/转化目标）', '时长选择（60s 内 / 3-5min / 5-10min）', '七大平台适配（抖音/TikTok/Shorts/Reels/B站/小红书/YouTube）', '五种语气预设（教育/娱乐/故事/推销/励志）', '分镜脚本（镜号+画面+旁白+字幕+音效）', '节奏标注', 'SSE 流式 Markdown 渲染', '全文一键复制'],
      example: {
        title: 'AI 视频脚本生成输入到输出示例',
        input: '主题: 5 个提升办公效率的隐藏技巧（第 1 个你绝对没想到）\n时长: 60s 以内\n平台: 抖音\n语气: 教育型 + 轻松幽默',
        output:
          '## 开场钩子 (0-3s)\n画面: 桌面堆满文件和便利贴的快切 → 突然清空只留一台笔记本。\n旁白:「你有没有觉得——明明忙了一天，真正做完的事却不超过三件？」\n\n## 镜头 1 (3-15s)\n画面: 特写手指在键盘上按下 Win+V 键。屏幕弹出剪贴板历史面板。\n旁白:「第一个隐藏技巧：Win+V 打开剪贴板历史，再也不用来回 Ctrl+C/V 切换。」\n\n## 镜头 2 (15-28s)\n…（后续分镜略）\n\n## 结尾 CTA (55-60s)\n画面: 创作者面对镜头微笑 + 屏幕弹出关注动画。\n旁白:「收藏这条视频，周一上班第一个试!」\n字幕: 点击关注 → 每周解锁更多效率技巧',
        inputLanguage: 'text',
        outputLanguage: 'markdown',
      },
    },
    en: {
      summary:
        'The AI Video Script Generator expands a video topic or core creative idea into a fully scene-planned, well-paced, structured shooting script ready to hand off to production and editing teams. It covers two duration specs — short-form (under 60 seconds, suitable for the fast-paced content of Douyin/TikTok/YouTube Shorts/Instagram Reels) and mid-to-long-form (3-10 minutes, suitable for deeper content on Bilibili/YouTube/Channels) — and adapts to seven target platforms: Douyin, TikTok, YouTube Shorts, Instagram Reels, Bilibili, Xiaohongshu Video, and YouTube. Ideal for independent creators wanting an executable shooting blueprint right after locking in a topic; brand marketing teams developing voiceover or narrative scripts for product launches, campaign promotions, and brand stories; educational explainer creators translating specialist content into accessible narrative structures; vlog creators planning the rhythm and emotional arc of daily footage; operations teams batch-producing script templates for feed ads and marketing placements; and corporate training teams writing scene breakdowns and narration for instructional videos. After duration, platform, and tone are selected, the AI auto-generates a complete script draft including an opening hook, scene blocks, visual direction, voiceover lines, subtitle cues, transition pacing, and a closing CTA.',
      input:
        'Four core parameters: video topic or core message (required), estimated duration (under 60s / 3-5 min / 5-10 min), target platform (Douyin / TikTok / YouTube Shorts / Instagram Reels / Bilibili / Xiaohongshu / YouTube), and script tone (Educational / Entertaining / Storytelling / Sales-oriented / Inspirational). The topic input field supports multi-line text and can include target audience profile, product key selling points or feature descriptions, story conflict or plot threads, knowledge point outline, conversion goals (e.g. drive link clicks, follows, comment engagement, purchase conversion), and brand tone constraints (e.g. "keep it witty," "highlight tech professionalism," "warm and healing vibe"). Duration selection directly affects script information density and pacing: short-form under 60s emphasizes a 3-second golden opening, dense information delivery, and a strong closing hook; 3-5 minute mid-form places a rhythm beat every 30-60 seconds with room for mini-climaxes; 5-10 minute long-form provides fuller space for buildup, development, and resolution. Platform selection affects opening strategy and delivery style: Douyin/TikTok emphasizes grabbing attention in the first 3 seconds, Bilibili allows some buildup, and YouTube long-form can guide viewers to subscribe more leisurely.',
      output:
        'A Markdown video shooting script typically organized in the following structure (the AI auto-adjusts section density and count based on duration and platform): Opening Hook — an attention-grabbing design for the first 3-5 seconds (a counterintuitive question, data shock, visual conflict, or benefit promise) with suggested visuals and subtitle coordination; Scene Blocks — shooting units segmented along the timeline, each containing: scene number, duration, visual description (composition, camera movement, color palette, key visual elements), voiceover / spoken lines, subtitle keyword hints, sound effect / BGM suggestions, and transition style; Pacing Notes — rhythm-change annotations at key turning points (speed up, slow down, silence, impact) to guide the editor in post-production; Closing CTA — ending lines guiding viewers to like, follow, comment, share, or click a link. Output is rendered via react-markdown + remark-gfm with clear hierarchical readability, and a one-click full-text copy button allows pasting the complete script into collaboration platforms like Feishu Docs or Notion for the production and editing teams to reference and execute. On generation failure, the output panel shows the specific error message while input parameters are preserved for easy retry after adjustment.',
      processing:
        'When the user clicks Generate, the page collects the four input parameters — video topic text (topic), duration option (duration, e.g. "short", "medium", "long"), platform identifier (platform, e.g. "tiktok", "youtube", "bilibili"), and tone option (tone) — together with the current UI locale, assembles them into a JSON payload, and sends it via fetch POST to the /api/ai-video-script endpoint with Content-Type set to application/json. Upon receiving the parameters, the server constructs an AI model system prompt: the duration constrains the total scene count and approximate length per scene, the platform adjusts opening strategy and delivery style, and the tone controls the overall language character. The model progressively returns script content via SSE streaming, and the frontend concurrently reads each SSE event via ReadableStream: TextDecoder decodes the byte stream into strings, JSON.parse extracts the content field as incremental text, and React state (prev + chunk.content) appends it to the accumulated result in real time. After streaming completes, react-markdown (with remark-gfm supporting GitHub Flavored Markdown extensions such as tables and task lists) renders the full Markdown text into a formatted document with hierarchical headings, lists, and code blocks. A full-text copy button uses navigator.clipboard.writeText to write the complete Markdown source to the clipboard, with the button briefly displaying "Copied" before resetting via setTimeout after 2 seconds. Request failures or server errors are handled uniformly in the fetch catch block: the error state is set to the backend-returned error message or a generic "Generation failed, please try again later" prompt, and the output area renders a red-background error card.',
      modes: ['Multi-line video topic input (supports audience / selling points / conversion goals)', 'Duration selection (under 60s / 3-5min / 5-10min)', '7-platform adaptation (Douyin/TikTok/Shorts/Reels/Bilibili/Xiaohongshu/YouTube)', '5 tone presets (Educational / Entertaining / Storytelling / Sales / Inspirational)', 'Scene script (number + visual + voiceover + subtitles + audio)', 'Pacing annotations', 'SSE streaming Markdown rendering', 'Full-text one-click copy'],
      example: {
        title: 'AI video script generation input-to-output example',
        input: 'Topic: 5 Hidden Productivity Hacks for Office Workers (you\'ll never believe #1)\nDuration: Under 60s\nPlatform: TikTok\nTone: Educational + Light Humor',
        output:
          '## Opening Hook (0-3s)\nVisual: Fast cuts of a messy desk piled with papers and sticky notes → suddenly cleared to just one laptop.\nVoiceover: "Ever feel like you were busy all day — but actually finished fewer than three real things?"\n\n## Scene 1 (3-15s)\nVisual: Close-up of fingers pressing Win+V keys. Clipboard history panel pops up on screen.\nVoiceover: "First hidden hack: Win+V opens clipboard history. Never juggle Ctrl+C/V back and forth again."\n\n## Scene 2 (15-28s)\n… (remaining scenes truncated)\n\n## Closing CTA (55-60s)\nVisual: Creator smiles at camera + follow animation pops up on screen.\nVoiceover: "Save this video and try the first one Monday morning!"\nSubtitle: Follow for weekly productivity hacks →',
        inputLanguage: 'text',
        outputLanguage: 'markdown',
      },
    },
  },

  'ai-meeting-minutes': {
    zh: {
      summary:
        'AI 会议纪要生成器用于将原始会议录音转写文本、人工速记、会议聊天记录或多语言讨论片段整理为格式标准、重点突出的专业会议纪要，大幅降低会后手工整理的时间成本，确保讨论要点、决策结论和行动项无遗漏。适合项目推进例会（Sprint Planning、Daily Standup、Sprint Review 等敏捷会议）、客户需求沟通与方案评审会议、跨部门协作与对齐会议、产品需求评审（PRD Review）与技术方案讨论、项目复盘与事故回顾会（Retrospective / Postmortem）、面试记录归档和上级一对一面谈备忘、远程团队 Zoom/Teams/飞书会议的自动转写后处理，以及学术研讨会 / 行业分享会的笔记整理。工具支持三种输出格式——详细纪要（完整记录讨论背景、各方观点、论证过程和结论，适合需要存档备查或向未参会者传达完整语境）、仅提取行动项（去粗取精，只输出谁在什么时间前需要完成什么，并附优先级和依赖说明，适合直接导入 Jira、Linear、Asana 等项目管理工具）和高管摘要（将数十分钟的讨论浓缩为 3-5 个核心要点，适合向高层进行快速同步）——用户根据纪要的阅读对象和交付场景选择最合适的格式。',
      input:
        '两个核心参数：原始会议记录文本（必填）和输出纪要格式（详细纪要 / 仅行动项 / 高管摘要）。原始文本可以来自多种渠道：飞书妙记、腾讯会议云录制、Zoom Transcript、Otter.ai 等工具的语音转写导出文本（通常包含说话人标签和时间戳）；会议期间记录的人工速记或要点笔记；Slack/飞书/企业微信等群聊中的文字讨论历史（可包含 @ 提及、引用回复和文件分享记录）；以及混合中英文或多位发言人的分段讨论内容。输入文本的格式不做严格要求——无论是有序的转写稿还是杂乱的速记碎片，AI 模型均会先做语义理解和主题聚合再生成结构化纪要。格式选项决定最终输出的详略程度和组织方式：详细纪要（Detailed Minutes）输出完整讨论脉络，适合存档和内部分享；仅行动项（Action Items Only）输出纯列表形式的待办，适合直接跟进行动闭环；高管摘要（Executive Summary）输出高层视角的核心结论和风险，适合向上汇报。',
      output:
        '一份结构化的 Markdown 格式会议纪要，根据所选输出格式包含不同板块组合。详细纪要模式下通常包含：会议基本信息（日期、参会人、时长占位）；会议摘要（一段 3-5 句的总览段落概括会议目的和核心结论）；关键讨论与要点（按议题分段，每段含有讨论背景、各方观点和达成的共识或分歧）；决策结论（明确列出会议中做出的每项决策、决策依据和表决情况）；行动项（每项包含任务描述、负责人、截止时间和优先级标记）；待澄清问题（会议中提出但未解决、需要在后续跟进的问题）。仅行动项模式下只输出行动项列表和简要的风险/阻塞备注。高管摘要模式下输出 3-5 个要点段落——每段一句话总结 + 关键背景 + 需要关注的风险或决策请求。输出以 react-markdown + remark-gfm 渲染为格式化可视文档，支持一键复制全文 Markdown 源码，便于粘贴至 Confluence、Notion、飞书文档、邮件正文或项目管理系统评论区。生成失败时在输出面板展示具体错误信息，输入文本保留在表单中供用户调整后重新提交。',
      processing:
        '用户点击生成后，页面将两个核心参数——原始会议文本（rawInput）和输出格式选项（formatType，如 "detailed""actions""executive"）——连同当前界面语言 locale 组装为 JSON 载荷，通过 fetch API 以 POST 方式发送至 /api/ai-meeting-minutes 端点。服务端首先检查参数完整性：原始文本不能为空，格式选项必须在支持列表中。通过后服务端构建 AI 模型 system prompt："You are a professional meeting minutes writer. Based on the raw meeting transcript or notes provided, generate structured meeting minutes in the specified format... The output must be in well-formatted Markdown." 根据格式类型不同，system prompt 中会加入不同的输出约束——"详细纪要"模式下强调"完整记录所有讨论点和决策过程，不得省略关键论据"；"仅行动项"模式下强调"严格只输出行动项列表，每条包含 who/what/when 三要素"；"高管摘要"模式下强调"限制在 5 个要点以内，每个要点的背景不超过 2 句话，聚焦业务影响和需要的决策"。模型按 SSE 流式逐步返回纪要内容，前端通过 ReadableStream 并发读取每个事件块：TextDecoder 解码字节流为字符串，JSON.parse 提取 content 字段，通过 React setState 函数 prev + chunk.content 将增量文本实时追加到输出面板。流式传输结束后，react-markdown（配合 remark-gfm 支持 GFM 表格、任务列表等扩展语法）渲染完整 Markdown 文本。复制按钮通过 navigator.clipboard.writeText 复制 Markdown 全文，复制成功后短��反馈"已复制"并在 2 秒后通过 setTimeout 恢复。错误处理统一在 fetch catch 块中：设置 error 状态并在输出区展示红色错误卡片，输入表单保留以便修改后重试。',
      modes: ['原始会议文本输入（支持转写稿/速记/聊天记录/多语言混合）', '三种输出格式（详细纪要 / 仅行动项 / 高管摘要）', '议题分段与主题聚合', '决策结论独立列出', '行动项（who/what/when/priority）', 'SSE 流式 Markdown 渲染', '全文一键复制', '格式切换不丢失输入'],
      example: {
        title: 'AI 会议纪要生成输入到输出示例',
        input: '原始记录:\n王明：登录页改版下周上线，我负责接口联调，这周五之前完成。\n李娜：好的，我这周把埋点加上。对了测试环境最近不太稳定，上周五挂了三次。\n王明：那我们周二先内部验证一遍，有问题提前修。\n张总：可以，周二验证完没问题周四灰度发布，先放 5% 流量观察。\n\n输出格式: 仅行动项',
        output:
          '## 行动项\n\n- **王明**: 完成登录接口联调（截止: 本周五），周二参与内部验证。\n- **李娜**: 完成登录页埋点添加（截止: 本周五），周二参与内部验证。\n- **张总**: 周二验证通过后，周四执行 5% 灰度发布。\n\n## 风险\n- 测试环境近一周稳定性较差（上周五三次宕机），需在周二验证前确认环境可用。',
        inputLanguage: 'text',
        outputLanguage: 'markdown',
      },
    },
    en: {
      summary:
        'The AI Meeting Minutes Generator transforms raw meeting audio transcripts, manual shorthand notes, meeting chat logs, or multilingual discussion fragments into professionally formatted, well-structured meeting minutes — drastically reducing the manual post-meeting organization effort while ensuring that discussion points, decisions, and action items are fully captured. Suitable for regular project meetings (Sprint Planning, Daily Standups, Sprint Reviews, and other agile ceremonies), client requirement discussions and solution review sessions, cross-team collaboration and alignment meetings, product requirement reviews (PRD Review) and technical design discussions, retrospectives and postmortems, interview record archival and manager one-on-one memos, post-processing of auto-transcripts from remote meetings on Zoom / Teams / Feishu, and note consolidation for academic seminars and industry talks. The tool supports three output formats — Detailed Minutes (complete record of discussion background, all viewpoints, argumentation, and conclusions, suitable for archival or communicating full context to non-attendees), Action Items Only (distills the discussion to a pure list of who needs to complete what by when, with priority and dependency notes, suitable for direct import into Jira, Linear, Asana, etc.), and Executive Summary (condenses tens of minutes of discussion into 3-5 core takeaways, suitable for rapid sync with leadership) — allowing users to select the most appropriate format based on the minutes\' audience and delivery context.',
      input:
        'Two core parameters: the raw meeting record text (required) and the desired output format (Detailed Minutes / Action Items Only / Executive Summary). The raw text can come from a variety of sources: voice-transcription export text from tools such as Feishu Minutes, Tencent Meeting Cloud Recording, Zoom Transcript, or Otter.ai (typically containing speaker labels and timestamps); manual shorthand notes or key-point jottings taken during the meeting; text discussion history from group chats on Slack / Feishu / WeCom (which may include @ mentions, quoted replies, and file-sharing records); and segmented mixed Chinese-English or multi-speaker discussion content. The format of the input text is not strictly required — whether it is an ordered transcript or messy shorthand fragments, the AI model first performs semantic understanding and topic clustering before generating structured minutes. The format option determines the level of detail and organizational approach of the final output: Detailed Minutes produce the full discussion arc, suitable for archival and internal sharing; Action Items Only produce a pure list of todos, suitable for immediate action-loop follow-up; Executive Summary produces high-level core conclusions and risks, suitable for upward reporting.',
      output:
        'A structured Markdown meeting minutes document whose section composition varies by the selected output format. In Detailed Minutes mode, the output typically includes: Meeting Basic Info (date, attendees, duration placeholders); Meeting Summary (a 3-5 sentence overview paragraph summarizing the meeting purpose and key conclusions); Key Discussions & Points (organized by agenda item, each containing discussion background, viewpoints from each party, and consensus or disagreement reached); Decisions Made (clearly listing each decision made during the meeting, its rationale, and any voting outcomes); Action Items (each containing task description, owner, due date, and priority flag); Open Questions (items raised during the meeting but unresolved, requiring follow-up). In Action Items Only mode, only the action-item list and brief risk/blocker notes are output. In Executive Summary mode, 3-5 key-point paragraphs are output — each with a one-sentence takeaway + essential context + risks or decisions requiring attention. Output is rendered as a formatted visual document via react-markdown + remark-gfm, with a one-click full-text copy button for pasting into Confluence, Notion, Feishu Docs, email body, or project management system comment fields. On generation failure, the output panel displays the specific error message while the input text remains in the form for user adjustment and resubmission.',
      processing:
        'When the user clicks Generate, the page collects the two core parameters — raw meeting text (rawInput) and output format option (formatType, e.g. "detailed", "actions", "executive") — together with the current UI locale, assembles them into a JSON payload, and sends it via fetch POST to the /api/ai-meeting-minutes endpoint. The server first checks parameter completeness: the raw text must not be empty, and the format option must be in the supported list. On passing validation, the server constructs an AI model system prompt: "You are a professional meeting minutes writer. Based on the raw meeting transcript or notes provided, generate structured meeting minutes in the specified format... The output must be in well-formatted Markdown." Different output constraints are injected into the system prompt depending on the format type — Detailed Minutes mode emphasizes "fully record all discussion points and decision processes, do not omit key arguments"; Action Items Only mode emphasizes "strictly output only the action-item list, each containing the three elements of who/what/when"; Executive Summary mode emphasizes "limit to 5 key points maximum, each point\'s background limited to 2 sentences, focus on business impact and decisions needed." The model progressively returns the minutes content via SSE streaming, and the frontend concurrently reads each event chunk via ReadableStream: TextDecoder decodes the byte stream into strings, JSON.parse extracts the content field, and React setState (prev + chunk.content) appends the incremental text to the output panel in real time. After streaming completes, react-markdown (with remark-gfm supporting GFM extensions such as tables and task lists) renders the full Markdown text. The copy button uses navigator.clipboard.writeText to copy the full Markdown source, briefly displaying "Copied" before resetting via setTimeout after 2 seconds. Error handling is unified in the fetch catch block: the error state is set and a red error card is displayed in the output area while the input form is preserved for retry after modification.',
      modes: ['Raw meeting text input (supports transcripts / shorthand / chat logs / mixed languages)', 'Three output formats (Detailed Minutes / Action Items Only / Executive Summary)', 'Agenda-based sectioning and topic clustering', 'Decisions listed independently', 'Action items (who / what / when / priority)', 'SSE streaming Markdown rendering', 'Full-text one-click copy', 'Format switching without losing input'],
      example: {
        title: 'AI meeting minutes generation input-to-output example',
        input: 'Raw record:\nMing: The login page redesign launches next week. I\'ll handle API integration and finish before this Friday.\nLina: Got it. I\'ll add analytics this week. Also, the testing environment has been unstable — it went down three times last Friday.\nMing: Let\'s do an internal validation on Tuesday; fix any issues early.\nZhang: Agreed. If Tuesday validation passes, we\'ll do a 5% canary release on Thursday.\n\nFormat: Action Items Only',
        output:
          '## Action Items\n\n- **Ming**: Complete login API integration (due: this Friday). Participate in Tuesday internal validation.\n- **Lina**: Complete login page analytics instrumentation (due: this Friday). Participate in Tuesday internal validation.\n- **Zhang**: On successful Tuesday validation, execute 5% canary release on Thursday.\n\n## Risks\n- Testing environment stability concerns (three outages last Friday); environment availability must be confirmed before Tuesday validation.',
        inputLanguage: 'text',
        outputLanguage: 'markdown',
      },
    },
  },

  'ai-excel-formula': {
    zh: {
      summary:
        'AI Excel 公式生成器用于将日常自然语言描述的数据处理需求智能转换为可直接在 Excel 或 Google Sheets 中使用的精确公式，消除手动查找函数语法和嵌套规则的低效过程。适合财务人员编写工资计算表、费用报销汇总、预算与实际差异分析、折旧摊销计算和多币种汇兑处理公式；运营分析人员在销售日报、用户留存报表、渠道 ROI 对比和活动效果分析中快速生成 SUMIFS / COUNTIFS / VLOOKUP / XLOOKUP / INDEX-MATCH 等多条件聚合与查找公式；人力资源人员在考勤统计、绩效考核评分、招聘漏斗和人员编制表中编写条件计算；项目经理在甘特图进度计算、资源分配统计和风险评分矩阵中生成自动化公式；数据分析师在数据清洗（TRIM / CLEAN / SUBSTITUTE 文本规范化）、异常值标注（IF / IFS / CONDITIONAL）、日期区间统计（DATEDIF / EOMONTH / NETWORKDAYS）等环节中快速获取公式和解读；以及不熟悉 Excel 函数生态的普通办公人员在面对日常表格计算需求时不再依赖逐一百度搜索"Excel 怎么按条件求和"。工具生成公式的同时会对每个参数进行解释、指出适用场景和潜在边界问题，并区分 Excel 与 Google Sheets 的函数兼容性差异。',
      input:
        '两个核心参数：自然语言计算需求描述（必填）和目标表格类型（Microsoft Excel 或 Google Sheets）。需求描述支持自由文本输入，可以包含以下信息：涉及的数据列及其含义（如"A 列是区域、B 列是销售额、C 列是日期"）；具体的计算逻辑和条件组合（如"当 A 列为\'华东\'且 C 列日期在 2026 年 5 月时，求对应 B 列的合计金额"）；文本匹配或模糊查找规则（如"从 E 列查找包含\'退款\'字样的行，并计算对应的 F 列金额"）；日期和时间计算需求（如"计算 G 列日期距离今天的自然天数，排除周末"）；跨表引用和数组计算（如"在 Sheet2 的 A:D 区域内，按当前表 A2 的值查找第 4 列"）；异常值或边界条件处理（如"如果结果为空则显示\'暂无数据\'"）。工具不要求使用标准术语，用户可以按自己习惯的语言风格描述，AI 会自动理解意图并匹配到合适的函数组合。表格类型选项用于区分 Excel 和 Google Sheets 的函数兼容性——例如 Google Sheets 支持 ARRAYFORMULA、QUERY、GOOGLEFINANCE 等特有函数，而 Excel 支持 XLOOKUP、TEXTJOIN、LET、LAMBDA 等较新函数，AI 会根据所选类型避免生成不兼容的公式并提示替代方案。',
      output:
        '一份包含三部分的 Markdown 格式结果：推荐公式——以代码块形式高亮展示可直接复制粘贴的公式文本（如 =SUMIFS(B:B, A:A, "华东", C:C, ">=2026-05-01", C:C, "<=2026-05-31")），外部包裹 Markdown 代码块（```）便于区分和复制；参数说明——逐参数分解公式结构，用自然语言解释每个参数的取值含义和数据类型要求（如"A:A 是条件判断区域，\'华东\'是匹配值，B:B 是求和区域"）；使用说明与注意事项——补充涵盖适用场景、预期行为、可能的边界情况及替代方案的说明，例如提示用户数组公式在旧版 Excel 中需按 Ctrl+Shift+Enter 输入、Google Sheets 中某些函数的行为与 Excel 略有差异（如 VLOOKUP 的近似匹配默认值等）、以及如果数据结构有变化时的公式调整方向。输出以 react-markdown + remark-gfm 渲染，保留标题层级、代码块高亮和列表格式。用户可一键复制完整内容（公式 + 解释 + 注意事项），或仅选中代码块内的公式单独复制。生成失败时在输出面板展示具体错误信息，输入需求描述保留在表单中以便调整措辞后重试。',
      processing:
        '用户点击生成后，页面将两个核心参数——计算需求描述文本（requirement）和目标表格类型（formulaType，如 "excel" 或 "sheets"）——与当前界面语言 locale 一起组装为 JSON 载荷，通过 fetch API 以 POST 方式发送至 /api/ai-excel-formula 端点。服务端首先执行基础校验：需求文本不能为空且不超过一定长度（防止将整篇文档作为输入导致生成质量下降），表格类型必须在支持的枚举列表中。校验通过后构建 AI 模型 system prompt："You are an expert Excel/Google Sheets formula engineer. Based on the user\'s natural-language calculation requirement and target spreadsheet type, generate the most efficient and accurate formula. Always output in three sections: (1) the recommended formula in a code block, (2) a parameter-by-parameter breakdown explaining each argument, and (3) usage notes covering context, edge cases, any platform-specific differences if applicable, and possible alternatives." 模型按 SSE 流式返回生成结果，前端通过 ReadableStream 并发读取每个事件块：TextDecoder 解码字节流为字符串，JSON.parse 提取 content 字段，通过 React setState 函数式更新 prev + chunk.content 实时追加到输出区域。流式传输结束后，react-markdown（配合 remark-gfm 支持代码块语法高亮和 GFM 表格/列表）渲染完整 Markdown 文本。复制按钮通过 navigator.clipboard.writeText 复制 Markdown 全文（包含公式、解释和注意事项），复制成功后按钮反馈"已复制"并在 2 秒后恢复。错误处理统一在 fetch catch 块中：网络异常或服务端错误均设置 error 状态字符串并在输出区渲染红色错误卡片，输入框保留用户的原始需求文本。',
      modes: ['自然语言需求描述（支持列名/条件/日期/查找/跨表等任意组合）', 'Microsoft Excel 公式模式', 'Google Sheets 公式模式（含 ARRAYFORMULA/QUERY 等专属函数）', '公式 + 参数逐项解释 + 注意事项三段式输出', '代码块高亮展示公式', '平台兼容性差异提示', 'SSE 流式 Markdown 渲染', '全文一键复制'],
      example: {
        title: 'AI Excel 公式生成输入到输出示例',
        input: '需求: A 列是销售区域（如华东、华南、华北），B 列是订单金额，C 列是订单日期（格式 YYYY-MM-DD）。需求：计算 2026 年 5 月华东区域的总订单金额。\n表格类型: Microsoft Excel',
        output:
          '## 推荐公式\n\n```excel\n=SUMIFS(B:B, A:A, "华东", C:C, ">=2026-05-01", C:C, "<=2026-05-31")\n```\n\n## 参数说明\n- **B:B** — 求和区域（订单金额列）。\n- **A:A** — 第一组条件判断区域（销售区域列）。\n- **"华东"** — 第一组条件的匹配值。\n- **C:C, ">=2026-05-01"** — 第二组条件：订单日期大于等于 5 月 1 日。\n- **C:C, "<=2026-05-31"** — 第三组条件：订单日期小于等于 5 月 31 日。\n\n## 注意事项\n- SUMIFS 的第一个参数是求和区域，后续参数按"条件区域, 条件"成对出现，与 SUMIF 参数顺序不同。\n- 如果数据量较大（超过数万行），建议将 B:B 等整列引用改为具体范围（如 B2:B5000）以提升计算效率。\n- 适用于 Excel 2007 及以上版本。Google Sheets 语法完全兼容。',
        inputLanguage: 'text',
        outputLanguage: 'markdown',
      },
    },
    en: {
      summary:
        'The AI Excel Formula Generator intelligently converts natural-language data-processing requirements into precise formulas ready to use directly in Excel or Google Sheets, eliminating the friction of manually searching for function syntax and nesting rules. Suitable for finance professionals writing salary calculation sheets, expense reimbursement summaries, budget-vs-actual variance analyses, depreciation/amortization calculations, and multi-currency conversion formulas; operations analysts quickly generating SUMIFS / COUNTIFS / VLOOKUP / XLOOKUP / INDEX-MATCH multi-condition aggregation and lookup formulas in daily sales reports, user retention dashboards, channel ROI comparisons, and campaign performance analyses; HR professionals writing conditional calculations for attendance statistics, performance review scoring, recruiting funnels, and headcount sheets; project managers generating automated formulas for Gantt chart progress calculations, resource allocation statistics, and risk scoring matrices; data analysts quickly obtaining formulas with interpretations for data cleaning (TRIM / CLEAN / SUBSTITUTE text normalization), outlier flagging (IF / IFS / CONDITIONAL), and date-range statistics (DATEDIF / EOMONTH / NETWORKDAYS); and general office users unfamiliar with the Excel function ecosystem who no longer need to search "how to conditional sum in Excel" for every everyday spreadsheet calculation need. The tool explains each parameter, points out applicable scenarios and potential edge cases, and distinguishes function compatibility differences between Excel and Google Sheets.',
      input:
        'Two core parameters: a natural-language calculation requirement description (required) and the target spreadsheet type (Microsoft Excel or Google Sheets). The requirement description supports free-text input and can include: the data columns involved and their meanings (e.g. "Column A is region, Column B is sales amount, Column C is date"); specific calculation logic and condition combinations (e.g. "sum Column B where Column A is \'East\' AND Column C falls within May 2026"); text matching or fuzzy lookup rules (e.g. "look up rows in Column E containing the word \'refund\' and sum the corresponding amounts in Column F"); date and time calculation needs (e.g. "calculate the number of calendar days between the date in Column G and today, excluding weekends"); cross-sheet references and array calculations (e.g. "in the range Sheet2!A:D, look up the value in A2 of the current sheet and return column 4"); and outlier or boundary condition handling (e.g. "display \'No data\' if the result is empty"). Standard terminology is not required — users can describe requirements in their own language style, and the AI automatically understands intent and matches it to the appropriate function combination. The spreadsheet type option distinguishes Excel from Google Sheets function compatibility — for example, Google Sheets supports unique functions such as ARRAYFORMULA, QUERY, and GOOGLEFINANCE, while Excel supports newer functions such as XLOOKUP, TEXTJOIN, LET, and LAMBDA. The AI avoids generating incompatible formulas for the selected type and suggests alternatives where appropriate.',
      output:
        'A Markdown result in three sections: Recommended Formula — displayed in a highlighted code block for direct copy-paste (e.g. =SUMIFS(B:B, A:A, "East", C:C, ">=2026-05-01", C:C, "<=2026-05-31")), wrapped in a Markdown code block (```) for easy visual distinction and copying; Parameter Breakdown — a parameter-by-parameter deconstruction of the formula structure, explaining in natural language the meaning and data-type requirements of each argument (e.g. "A:A is the criteria range, \'East\' is the match value, B:B is the sum range"); Usage Notes & Cautions — supplementary notes covering applicable scenarios, expected behavior, possible edge cases, and alternative approaches, such as reminders that array formulas require Ctrl+Shift+Enter in older Excel, certain functions behave slightly differently in Google Sheets (e.g. VLOOKUP approximate match default), and directions for adjusting the formula if the data structure changes. Output is rendered via react-markdown + remark-gfm, preserving heading hierarchy, code block highlighting, and list formatting. Users can copy the full content with one click (formula + explanation + notes), or selectively copy only the formula from within the code block. On generation failure, the output panel displays the specific error message while the requirement description remains in the form for rewording and retry.',
      processing:
        'When the user clicks Generate, the page collects the two core parameters — the calculation requirement description text (requirement) and the target spreadsheet type (formulaType, e.g. "excel" or "sheets") — together with the current UI locale, assembles them into a JSON payload, and sends it via fetch POST to the /api/ai-excel-formula endpoint. The server first performs basic validation: the requirement text must not be empty and must not exceed a certain length (to prevent entire documents being used as input and degrading generation quality), and the spreadsheet type must be in the supported enum list. On passing validation, the server constructs an AI model system prompt: "You are an expert Excel/Google Sheets formula engineer. Based on the user\'s natural-language calculation requirement and target spreadsheet type, generate the most efficient and accurate formula. Always output in three sections: (1) the recommended formula in a code block, (2) a parameter-by-parameter breakdown explaining each argument, and (3) usage notes covering context, edge cases, any platform-specific differences if applicable, and possible alternatives." The model progressively returns the generated result via SSE streaming, and the frontend concurrently reads each event chunk via ReadableStream: TextDecoder decodes the byte stream into strings, JSON.parse extracts the content field, and React setState (prev + chunk.content) appends the incremental text to the output area in real time. After streaming completes, react-markdown (with remark-gfm supporting code block syntax highlighting and GFM tables/lists) renders the full Markdown text. The copy button uses navigator.clipboard.writeText to copy the full Markdown (containing the formula, explanation, and notes), briefly displaying "Copied" before resetting via setTimeout after 2 seconds. Error handling is unified in the fetch catch block: network exceptions or server errors both set an error state string and render a red error card in the output area while the input field preserves the user\'s original requirement text.',
      modes: ['Natural-language requirement (supports any combination: columns / conditions / dates / lookups / cross-sheet)', 'Microsoft Excel formula mode', 'Google Sheets formula mode (supports ARRAYFORMULA / QUERY etc.)', 'Three-section output: formula + parameter breakdown + notes', 'Formula displayed in highlighted code block', 'Platform compatibility difference alerts', 'SSE streaming Markdown rendering', 'Full-text one-click copy'],
      example: {
        title: 'AI Excel formula generation input-to-output example',
        input: 'Requirement: Column A is sales region (East, South, North), Column B is order amount, Column C is order date (format YYYY-MM-DD). Calculate the total order amount for the East region in May 2026.\nSpreadsheet type: Microsoft Excel',
        output:
          '## Recommended Formula\n\n```excel\n=SUMIFS(B:B, A:A, "East", C:C, ">=2026-05-01", C:C, "<=2026-05-31")\n```\n\n## Parameter Breakdown\n- **B:B** — Sum range (order amount column).\n- **A:A** — First criteria range (sales region column).\n- **"East"** — First criteria match value.\n- **C:C, ">=2026-05-01"** — Second criteria pair: order date on or after May 1.\n- **C:C, "<=2026-05-31"** — Third criteria pair: order date on or before May 31.\n\n## Notes\n- In SUMIFS, the first argument is the sum range, followed by pairs of (criteria range, criteria). This order differs from SUMIF.\n- For large datasets (tens of thousands of rows or more), consider replacing full-column references like B:B with specific ranges (e.g. B2:B5000) to improve performance.\n- Compatible with Excel 2007+ and Google Sheets (identical syntax).',
        inputLanguage: 'text',
        outputLanguage: 'markdown',
      },
    },
  },

  'ai-regex': {
    zh: {
      summary:
        'AI 正则表达式生成器用于将自然语言描述的文本匹配、查找、替换或提取需求智能转换为准确、可用的正则表达式，支持 JavaScript、Python、Java、Go、PCRE 和 Ruby 六种主流正则引擎风格的语法适配。适合前端开发者编写表单输入校验规则（邮箱格式、手机号、身份证号、URL、IP 地址、日期格式等字段级实时验证），后端开发者在日志分析和数据管道中提取或过滤结构化字段（从 Nginx access log 中提取 IP 和状态码、从应用日志中匹配错误堆栈），数据分析师和爬虫工程师在 HTML/JSON/CSV 文本中解析非标准格式的字段值、清洗噪声字符或提取目标数据片段，运维工程师在批量文件重命名、配置迁移和脚本编写中使用正则进行字符串操作，测试工程师在自动化测试中编写断言模式验证输出格式，以及任何需要在编辑器（VS Code、Sublime）、命令行（grep、sed、awk）或数据库（MySQL REGEXP、PostgreSQL ~）中使用正则搜索替换的开发者。工具不仅生成正则表达式本身，还会以结构化方式解释每个语法组件的含义、提供匹配和不匹配的示例对照、指出常见的边界遗漏（如未处理空串、未限制长度范围、未转义特殊字符等）并提供修正建议。建议用户在生成正则后，将结果粘贴到本网站的 Regex Tester 工具中，使用真实的正面和负面样例进行充分验证。',
      input:
        '两个核心参数：匹配需求描述（必填）和正则风格 / 引擎（JavaScript / Python / Java / Go / PCRE / Ruby）。需求描述采用自由文本输入，用户可以用自然语言详细说明要匹配的内容和约束条件，例如：目标文本类型（如邮箱地址、手机号码、URL、日期格式、IP 地址、十六进制颜色码、身份证号码等预设模式，或完全自定义的文本模式）；允许的字符范围（如"只允许字母和数字""包含中文和英文""排除特殊符号"）；长度限制（如"长度 6-20 位""至少 8 个字符""不限长度"）；前缀或后缀约束（如"以 http 或 https 开头""以 .jpg、.png 或 .gif 结尾""必须包含 # 号"）；是否需要捕获特定的子组（如"提取域名部分""提取年月日三个捕获组""不需要捕获组只做整体匹配"）；多行匹配行为（如"逐行匹配""跨行匹配""匹配整个文本"）；排除条件（如"不匹配纯数字""排除 .gov 结尾的邮箱""不匹配 test 开头的字符串"）；以及特殊规则（如"忽略大小写""全局匹配""Unicode 字符支持""允许空字符串"）。风格选项用于适配不同编程语言或引擎的正则语法差异——例如 JavaScript 本身不支持后行断言（lookbehind）在 ES2018 之前的版本，Python 需要特殊处理 Unicode 标志，Java 需要双反斜杠转义，Go 的 RE2 引擎不支持反向引用和环视等高级特性，PCRE 支持最丰富的扩展语法。工具会根据所选风格自动调整生成的正则表达式的语法细节，避免生成不兼容的模式。',
      output:
        '一份结构化的 Markdown 格式输出，通常包含以下板块：正则表达式——以代码块形式展示生成的正则字面量或构造函数（JavaScript 风格为 /pattern/flags、Python 风格为 r\'pattern\'、Java 风格为 String regex = "pattern" 等，适配所选引擎的代码习惯）；模式分解说明——逐个语法组件（^、$、[]、()、(?:)、(?=)、\d、\w、{n,m}、*+? 量词、| 分支等）的语义解释，用表格或列表形式清晰对应每个符号与其功能，帮助用户理解而不仅是复制使用；匹配示例——提供 3-5 个正面样例（应该通过匹配的字符串）和 3-5 个负面样例（应该被拒绝的字符串），以直观对照形式帮助用户判断正则是否满足实际需求；边界提醒——指出当前模式可能存在的边界问题（如"该模式允许空字符串通过""允许 . 匹配任何单个字符可能产生误判""未限制域名 TLD 长度"）以及建议的加固方向。输出以 react-markdown + remark-gfm 渲染为格式化的代码块和列表，同时提供一键复制完整结果按钮。生成失败时输出面板展示具体错误信息并保留输入表单。',
      processing:
        '用户点击生成后，页面将两个核心参数——匹配需求描述文本（requirement）和正则风格引擎选择（flavor，取值为 "javascript""python""java""go""pcre""ruby"）——连同当前界面语言 locale 一起组装为 JSON 载荷，通过 fetch API 以 POST 方式发送至 /api/ai-regex 端点。服务端首先校验参数：需求文本不能为空，风格值必须在支持的引擎列表中。校验通过后构建 AI 模型 system prompt："You are a senior software engineer specialized in regular expressions across multiple programming languages. Based on the user\'s matching requirement description and the target regex engine/flavor, generate an accurate and efficient regular expression. Your response must include: (1) the generated regex in a code block with the engine-appropriate syntax; (2) a component-by-component breakdown explaining each syntax element; (3) positive match examples and negative non-match examples; (4) edge-case reminders and hardening suggestions specifically for this pattern. Adjust syntax details (escaping, lookbehind support, backreference support, Unicode handling, negation patterns) for the specified flavor." 模型按 SSE 流式逐步返回完整结果，前端通过 ReadableStream 并发读取每个事件块：TextDecoder 解码字节流，JSON.parse 提取 content 字段，通过 React setState 函数式更新 prev + chunk.content 实时追加到输出区域。流式传输结束后，react-markdown（配合 remark-gfm 渲染代码块、表格和列表）对完整 Markdown 文本进行渲染展示。复制按钮通过 navigator.clipboard.writeText 复制完整 Markdown 源文本，复制成功后按钮短暂显示"已复制"并在 2 秒后恢复。错误处理在 catch 块中统一捕获：设置 error 状态并渲染红色错误卡片，输入框保留用户原始需求文本。页面自身不执行所生成正则的语法验证或样例匹配测试，仅负责参数组织、生成请求、流式接收、Markdown 渲染和复制功能，用户应在 Regular Expression Tester 工具中用真实数据验证所有生成的模式。',
      modes: ['自然语言匹配需求（字符/长度/前后缀/捕获/排除/多行等任意组合）', '六种正则引擎风格（JavaScript / Python / Java / Go / PCRE / Ruby）', '模式逐组件分解说明', '正面 & 负面匹配样例对照', '边界遗漏检查与加固建议', 'SSE 流式 Markdown 渲染', '全文一键复制'],
      example: {
        title: 'AI 正则表达式生成输入到输出示例',
        input: '匹配需求: 匹配合法电子邮件地址。要求：支持常用的个人和企业邮箱（如 Gmail、Outlook、公司域名邮箱），允许大小写字母、数字、点号、下划线和连字符在 @ 前出现，域名部分允许多级子域名，顶级域名至少两个字母。排除没有 @ 符号、@ 前后为空、或含有连续点号的无效格式。\n正则风格: JavaScript',
        output:
          '## 正则表达式\n\n```javascript\n/^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$/\n```\n\n## 模式分解\n- `^` — 匹配字符串开头。\n- `[a-zA-Z0-9._%+-]+` — 本地部分：允许字母、数字和 . _ % + - 字符，至少一个。\n- `@` — 必须包含 @ 符号。\n- `[a-zA-Z0-9.-]+` — 域名部分：允许字母、数字、点号和连字符，至少一个。\n- `\\.` — 顶级域名前的点号（转义为字面量）。\n- `[a-zA-Z]{2,}` — 顶级域名：仅允许字母，至少 2 个字符。\n- `$` — 匹配字符串结尾。\n\n## 匹配示例\n✅ user@example.com\n✅ first.last@sub.example.co.uk\n✅ user+tag@domain.com\n❌ user@domain（缺少 TLD）\n❌ @domain.com（本地部分为空）\n❌ user..name@domain.com（连续点号）\n\n## 边界提醒\n- 该正则允许域名中出现连续连字符（如 user@dom--ain.com），如需排除可将域名部分改为 `(?:[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9])\\.`。\n- 顶级域名最大长度在实际中应 ≤ 63 字符，可添加 {2,63} 约束。\n- 如需在表单中做严格校验，建议先用该正则做格式过滤，再通过发送验证邮件确认地址真实有效。',
        inputLanguage: 'text',
        outputLanguage: 'markdown',
      },
    },
    en: {
      summary:
        'The AI Regex Generator intelligently converts natural-language text matching, search, replace, or extraction requirements into accurate, usable regular expressions, supporting syntax adaptation across six mainstream regex engine flavors: JavaScript, Python, Java, Go, PCRE, and Ruby. Suitable for frontend developers writing form input validation rules (field-level real-time validation of email format, phone numbers, ID numbers, URLs, IP addresses, date formats, etc.); backend developers extracting or filtering structured fields in log analysis and data pipelines (extracting IPs and status codes from Nginx access logs, matching error stack traces from application logs); data analysts and web scraping engineers parsing non-standard-format field values, cleaning noise characters, or extracting target data fragments from HTML/JSON/CSV text; operations engineers using regular expressions for batch file renaming, configuration migration, and scripting; QA engineers writing assertion patterns in automated tests to validate output formats; and any developer needing regex for search-and-replace in editors (VS Code, Sublime), command-line tools (grep, sed, awk), or databases (MySQL REGEXP, PostgreSQL ~). Beyond generating the regex itself, the tool structurally explains the meaning of each syntax component, provides matching and non-matching example comparisons, identifies common edge omissions (such as not handling empty strings, failing to limit length ranges, not escaping special characters, etc.), and offers hardening suggestions. Users are encouraged to paste the generated pattern into the site\'s Regex Tester tool and thoroughly validate it against real positive and negative samples.',
      input:
        'Two core parameters: a matching requirement description (required) and the regex flavor / engine (JavaScript / Python / Java / Go / PCRE / Ruby). The requirement description uses free-text input; users can describe in detail what to match along with constraints, such as: target text type (preset patterns like email address, phone number, URL, date format, IP address, hex color code, ID card number, or fully custom text patterns); allowed character range (e.g. "only letters and digits," "contains Chinese and English," "exclude special characters"); length limits (e.g. "length 6-20 characters," "at least 8 characters," "unlimited length"); prefix or suffix constraints (e.g. "starts with http or https," "ends with .jpg, .png, or .gif," "must contain a # sign"); whether specific subgroups need to be captured (e.g. "extract the domain part," "extract year/month/day as three capture groups," "no capture groups needed, just full-match validation"); multiline matching behavior (e.g. "match line by line," "cross-line match," "match the entire text"); exclusion conditions (e.g. "do not match pure digits," "exclude .gov addresses," "do not match strings starting with test"); and special rules (e.g. "case-insensitive," "global matching," "Unicode character support," "allow empty strings"). The flavor option adapts to syntax differences across programming languages or regex engines — for example, JavaScript lacked native lookbehind support before ES2018, Python requires special Unicode flag handling, Java requires double-backslash escaping, Go\'s RE2 engine does not support backreferences or lookarounds, and PCRE supports the richest set of extended syntax. The tool automatically adjusts the generated regex\'s syntax details based on the selected flavor to avoid producing incompatible patterns.',
      output:
        'A structured Markdown output typically containing the following sections: Regular Expression — the generated regex literal or constructor expression displayed in a code block with engine-appropriate syntax (JavaScript style: /pattern/flags; Python style: r\'pattern\'; Java style: String regex = "pattern", etc., adapted to the selected engine\'s coding conventions); Pattern Breakdown — a semantic explanation of each syntax component (^, $, [], (), (?:), (?=), \\d, \\w, {n,m}, *+? quantifiers, | alternation, etc.) clearly mapped to each symbol\'s function in table or list format, helping users understand rather than just copy-paste; Match Examples — 3-5 positive examples (strings that should pass the match) and 3-5 negative examples (strings that should be rejected), presented in a side-by-side comparison to help users assess whether the regex meets real requirements; Edge Case Reminders — noting potential boundary issues in the current pattern (e.g. "this pattern allows empty strings to pass," "allowing . to match any single character may cause false positives," "domain TLD length is not capped") along with suggested hardening directions. Output is rendered via react-markdown + remark-gfm into formatted code blocks and lists, with a one-click full-result copy button. On generation failure, the output panel displays the specific error message while preserving the input form.',
      processing:
        'When the user clicks Generate, the page collects the two core parameters — matching requirement description text (requirement) and regex flavor/engine selection (flavor, one of "javascript", "python", "java", "go", "pcre", "ruby") — together with the current UI locale, assembles them into a JSON payload, and sends it via fetch POST to the /api/ai-regex endpoint. The server first validates the parameters: the requirement text must not be empty, and the flavor value must be in the supported engine list. On passing validation, the server constructs an AI model system prompt: "You are a senior software engineer specialized in regular expressions across multiple programming languages. Based on the user\'s matching requirement description and the target regex engine/flavor, generate an accurate and efficient regular expression. Your response must include: (1) the generated regex in a code block with the engine-appropriate syntax; (2) a component-by-component breakdown explaining each syntax element; (3) positive match examples and negative non-match examples; (4) edge-case reminders and hardening suggestions specifically for this pattern. Adjust syntax details (escaping, lookbehind support, backreference support, Unicode handling, negation patterns) for the specified flavor." The model progressively returns the full result via SSE streaming, and the frontend concurrently reads each event chunk via ReadableStream: TextDecoder decodes the byte stream, JSON.parse extracts the content field, and React setState (prev + chunk.content) appends the incremental text to the output area in real time. After streaming completes, react-markdown (with remark-gfm rendering code blocks, tables, and lists) renders the full Markdown text for display. The copy button uses navigator.clipboard.writeText to copy the complete Markdown source text, briefly displaying "Copied" before resetting via setTimeout after 2 seconds. Error handling is unified in the catch block: the error state is set and a red error card is rendered while the input field preserves the user\'s original requirement text. The page itself does not perform regex syntax validation or sample-match testing of generated patterns — it handles only parameter organization, generation requests, streaming receipt, Markdown rendering, and copying. Users should verify all generated patterns with real data in the Regex Tester tool.',
      modes: ['Natural-language matching requirement (any combination: chars / length / prefixes / captures / exclusions / multiline)', 'Six regex engine flavors (JavaScript / Python / Java / Go / PCRE / Ruby)', 'Component-by-component pattern breakdown', 'Positive & negative match example comparison', 'Edge-case omission detection and hardening suggestions', 'SSE streaming Markdown rendering', 'Full-text one-click copy'],
      example: {
        title: 'AI regex generation input-to-output example',
        input: 'Requirement: Match valid email addresses. Support common personal and corporate emails (Gmail, Outlook, company domain emails). Allow uppercase and lowercase letters, digits, dots, underscores, and hyphens before the @ sign. Domain part allows multiple levels of subdomains. TLD must be at least two letters. Exclude invalid formats: missing @, empty local or domain part, or consecutive dots.\nFlavor: JavaScript',
        output:
          '## Regular Expression\n\n```javascript\n/^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$/\n```\n\n## Pattern Breakdown\n- `^` — Match start of string.\n- `[a-zA-Z0-9._%+-]+` — Local part: allows letters, digits, and . _ % + - characters; at least one.\n- `@` — Required @ symbol.\n- `[a-zA-Z0-9.-]+` — Domain part: allows letters, digits, dots, and hyphens; at least one.\n- `\\.` — Dot before TLD (escaped as literal).\n- `[a-zA-Z]{2,}` — TLD: letters only, at least 2 characters.\n- `$` — Match end of string.\n\n## Match Examples\n✅ user@example.com\n✅ first.last@sub.example.co.uk\n✅ user+tag@domain.com\n❌ user@domain (missing TLD)\n❌ @domain.com (empty local part)\n❌ user..name@domain.com (consecutive dots)\n\n## Edge Case Notes\n- This pattern allows consecutive hyphens in the domain (e.g. user@dom--ain.com). To exclude, change the domain part to: `(?:[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9])\\.`.\n- TLD maximum length should be ≤ 63 characters in practice; consider adding {2,63} constraint.\n- For strict form validation, it\'s recommended to use this regex for format filtering first, then send a verification email to confirm the address is genuinely valid.',
        inputLanguage: 'text',
        outputLanguage: 'markdown',
      },
    },
  },

  'ai-code-reviewer': {
    zh: {
      summary:
        'AI 代码审查工具用于对粘贴的代码片段进行质量、性能、安全性和可维护性审查，适合在正式提交 Pull Request 前做快速自查，也适合学习他人代码时获得结构化反馈。它可以帮助前端、后端和全栈开发者发现潜在空值问题、异常处理遗漏、重复逻辑、复杂度过高、命名不清、资源泄漏、异步竞态、性能浪费和常见安全风险。工具不会替代真实代码评审，但可以作为提交前的第一轮检查，把明显问题提前暴露出来。',
      input:
        '待审查的代码文本、代码语言和审查关注点。代码可以是一个函数、组件、接口处理器、工具方法、样式片段或配置逻辑；语言选项支持自动识别，也可以指定 JavaScript、TypeScript、React、Python、Java、Go、Rust、C++、CSS/SCSS 等。审查关注点用于控制反馈语气和重点，例如建设性建议、严格挑剔、新手友好或性能优化导向。',
      output:
        '一份 Markdown 格式的代码审查报告，通常包含总体评价、主要问题、风险等级、可改进建议、可能的重构方向和示例代码。输出会以段落、列表和代码块形式渲染；完整报告可以一键复制，报告中的代码块也支持单独复制，便于把建议带回编辑器或 PR 评论中继续处理。',
      processing:
        '点击开始审查后，页面将 code、codeLang、tone 和当前语言提交到 /api/ai-code-reviewer，并读取服务端 SSE 流式响应。每个 data 片段会被解析为 JSON，content 字段实时追加到结果文本中；最终通过 react-markdown 和 remark-gfm 渲染。代码块使用 Prism 高亮展示，并提供局部复制按钮。页面本身不执行静态分析或编译，只负责输入组织、请求提交、流式接收、Markdown 渲染和复制。',
      modes: ['多语言代码审查', '自动语言识别', '审查关注点选择', '流式 Markdown 报告', '代码块高亮', '报告与代码块复制'],
      example: {
        title: '代码审查输入到输出示例',
        input: '语言: TypeScript\n关注点: Performance Focus\n\nfunction findUser(users, id) {\n  return users.filter(user => user.id === id)[0];\n}',
        output:
          '## 主要问题\n- 使用 `filter(...)[0]` 会遍历完整数组，即使已经找到目标用户。\n- `users` 和 `id` 缺少类型声明，调用方传入异常数据时不容易发现。\n\n## 建议\n```ts\nfunction findUser(users: User[], id: string) {\n  return users.find((user) => user.id === id);\n}\n```',
        inputLanguage: 'typescript',
        outputLanguage: 'markdown',
      },
    },
    en: {
      summary:
        'The AI Code Reviewer analyzes pasted code snippets for quality, performance, security, and maintainability issues. It is useful for quick self-review before opening a Pull Request and for getting structured feedback while learning unfamiliar code. It can help frontend, backend, and full-stack developers spot potential null-handling bugs, missing error handling, duplicated logic, excessive complexity, unclear naming, resource leaks, async race conditions, performance waste, and common security risks. It does not replace human review, but it works well as a first pass before submission.',
      input:
        'The code to review, the code language, and the review focus. The code can be a function, component, API handler, utility method, style snippet, or configuration logic. The language selector supports auto-detect or explicit choices such as JavaScript, TypeScript, React, Python, Java, Go, Rust, C++, and CSS/SCSS. The review focus controls tone and priority, such as constructive suggestions, strict critique, beginner-friendly guidance, or performance-oriented feedback.',
      output:
        'A Markdown code review report, typically including an overall assessment, key issues, risk level, improvement suggestions, possible refactoring direction, and example code. The output is rendered as paragraphs, lists, and code blocks. The full report can be copied with one click, and code blocks inside the report can be copied separately for use in an editor or PR comment.',
      processing:
        'When review starts, the page submits code, codeLang, tone, and current language to /api/ai-code-reviewer, then reads the server-sent event stream. Each data chunk is parsed as JSON and its content field is appended to the result text in real time. The final result is rendered through react-markdown and remark-gfm. Code blocks are highlighted with Prism and include local copy buttons. The page itself does not run static analysis or compilation; it handles input assembly, request submission, streaming, Markdown rendering, and copying.',
      modes: ['Multi-language code review', 'Auto language detection', 'Review focus selection', 'Streaming Markdown report', 'Highlighted code blocks', 'Report and code-block copy'],
      example: {
        title: 'Code review input-to-output example',
        input: 'Language: TypeScript\nFocus: Performance Focus\n\nfunction findUser(users, id) {\n  return users.filter(user => user.id === id)[0];\n}',
        output:
          '## Key Issues\n- `filter(...)[0]` traverses the full array even after the target user has been found.\n- `users` and `id` have no type annotations, making invalid caller data harder to catch.\n\n## Suggestion\n```ts\nfunction findUser(users: User[], id: string) {\n  return users.find((user) => user.id === id);\n}\n```',
        inputLanguage: 'typescript',
        outputLanguage: 'markdown',
      },
    },
  },
};
